### ISSUE TITLE
Let's create a Waffle.io to keep track of progress

### ISSUE THREAD

**Issue by ManeBit** [emreakay/CodeIgniter-Aauth#100]
https://waffle.io/

I've used this simple storyboard add-on for a couple of my private repos.

@emreakay It's very handy especially for large team projects. I'd recommend opening one up,

**Comment by emreakay** [comment]
@ManeBit i have opened up :+1:

**Comment by emreakay** [comment]
have anybody used it?

**Comment by REJack** [comment]
@emreakay i would love to use it, but i need an invite from you :smile:

**Comment by ManeBit** [comment]
@emreakay same here

**Comment by emreakay** [comment]
can you add your e-mail adress to as comment

**Comment by REJack** [comment]
@emreakay my mail address is info@rejack.de & please create a new release :smile:

**Comment by ManeBit** [comment]
@emreakay manebit@zbs.com

**Comment by emreakay** [comment]
Hi everyone;

You can join us from here :dancer: 

waffle.io is gonna be very useful for us

https://waffle.io/emreakay/CodeIgniter-Aauth/join

**Comment by REJack** [comment]
@ManeBit can we close this issue?

**Comment by ManeBit** [comment]
Done
