### ISSUE TITLE
Database relations?

### ISSUE THREAD

**Issue by SergiX44** [emreakay/CodeIgniter-Aauth#103]
Can i create relations between tables? Which fields i need to put in relation?

**Comment by REJack** [comment]
> Here some Aauth examples:
> Aauth use user_id and group_id for relations between users and groups.
> Aauth use group_id and perm_id for relations between groups and perms.
> Aauth use user_id and perm_id for relations between users and perms.

like this you can use 
group_name & perm_name are not so good but it would work or 
group_id, perm_id or user_id to create a relation

**Comment by SergiX44** [comment]
Thanks!
