### ISSUE TITLE
Web Site for Aauth

### ISSUE THREAD

**Issue by emreakay** [emreakay/CodeIgniter-Aauth#104]
Hi Aauth comunity.
I want to create a webpage for aauth. Actualy i t can be simple.
We can have Default page for introducing Aauth, Wiki page, Contribitiors page and success history to write who used Aauth with which project

I can buy domain.
Who can give support for hosting?
And who can design and manage the website?

**Comment by ibrahimuslu** [comment]
I have an hosting
Stonehosting.net

I can host it

18 Oca 2016 Pzt, saat 23:38 tarihinde Emre Akay <notifications@github.com>
şunu yazdı:

**Comment by BlueFreakLP** [comment]
https://pages.github.com/
That´s better and safe, so you can trust the Hosting, that it is really up.

**Comment by BlueFreakLP** [comment]
btw. https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by REJack** [comment]
github pages are the best solution for us. 

Von meinem iPhone gesendet

**Comment by REJack** [comment]
or we can use readthedocs.org with [Alternate Domains](http://read-the-docs.readthedocs.org/en/latest/alternate_domains.html)

**Comment by omkartapale** [comment]
Better to go with github. Its convenient in all manner

**Comment by omkartapale** [comment]
Better to go with github. Its convenient in all manner

**Comment by emreakay** [comment]
ok @ibrahimuslu thank you for your offer. We will use github pages. 
So now who can design page?

**Comment by REJack** [comment]
@emreakay for the Docs i would use [GitBook](https://www.gitbook.com).

Does somebody have ideas for the page design?
