### ISSUE TITLE
Can i use any payment library with aauth ?

### ISSUE THREAD

**Issue by imarshmultani** [emreakay/CodeIgniter-Aauth#105]
Hey , as i'm using this library for a big project , i also was thinking to add payment options inside the site , and wanted to know if it's possible to integrate payment methods along this script? . if yes then which one can i use inside this one ? .

**Comment by BlueFreakLP** [comment]
You should write your own libary.  Aauth is only for usermangement and authentication.

**Comment by REJack** [comment]
i would never integrate a payment method in an authentication system like aauth.

keep your payment and authentication systems seperated, it would be a big risk for you.

**Comment by REJack** [comment]
is your question awnsered? if yes pls close this issue :smile:
