### ISSUE TITLE
check if passoword is correct

### ISSUE THREAD

**Issue by SergiX44** [emreakay/CodeIgniter-Aauth#106]
how can i check if an entered password of a user is correct? I need to do a change passoword, the page will ask the current password, the new password and repeat of the new password. But how i can check if the current password is correct?

**Comment by REJack** [comment]
you need to create an ajax hash_password function and check the hashed string

Von meinem iPhone gesendet

**Comment by paulcanning** [comment]
@REJack that is a terrible idea. If you want to let users change their password, you should assume they are already logged in. In that case, you can verify the current password by passing it to the `is_loggedin()` function possibly (or writing a similar function that simply returns true/false?

**Comment by REJack** [comment]
@paulcanning its not a terrible idea, there are 2 ways for this, some peoples likes ajax and other hate it :D

1. with ajax (interactive) seen on may pages.
2. with php (non interactive) with (`get_user()` & `hash_password()`) u can create a check before the user get updated.

i create a `check_password` function, then its easy to create a  `Confirm password to continue`-page like GitHub has it on `Personal access tokens -> Generate new token`.
