### ISSUE TITLE
PHP7 - Methods with the same name as their class will not be constructors in a future version of PHP; ReCaptcha has a deprecated constructor  Filename: helpers/recaptchalib_helper.php

### ISSUE THREAD

**Issue by harishningegowda** [emreakay/CodeIgniter-Aauth#107]
I just upgraded to PHP7. And this is the error I am getting.

A PHP Error was encountered

Severity: 8192

Message: Methods with the same name as their class will not be constructors in a future version of PHP; ReCaptcha has a deprecated constructor

Filename: helpers/recaptchalib_helper.php

Line Number: 42

Backtrace:

File: path\to\my\app\application\libraries\Aauth.php
Line: 103
Function: helper

File: path\to\my\app\application\controllers\example.php
Line: 17
Function: library

File: path\to\my\app\index.php
Line: 292
Function: require_once

**Comment by REJack** [comment]
thx for the info i take a look over it

**Comment by engrmahabub** [comment]
please fix it quick

**Comment by BuzzAstro** [comment]
please fix this error

**Comment by REJack** [comment]
@harishningegowda, @engrmahabub & @BuzzAstro Guys here is your fix:smiley: 

i changed the `ReCaptcha` function to `__construct` to prevent this failure and make the code proper.
