### ISSUE TITLE
Update User

### ISSUE THREAD

**Issue by amournet** [emreakay/CodeIgniter-Aauth#109]
I cann't update an user, after reviewing your source code, i think that the problem is your checking valid function in the function "update_user",  e.x: if i change the name, not change email, and save this data, your function check this existing email, this is wrong, but this is right if i create a new user,
you understand what i say !!! :))

**Comment by REJack** [comment]
i understand what you mean, but you have a little mistake. i think you send the existing email every update, but you need to set [$email](https://github.com/emreakay/CodeIgniter-Aauth/blob/master/application/libraries/Aauth.php#L782) to `FALSE` then it skips the email checks.

**Comment by amournet** [comment]
when i update an user info, i have to check the email, the name... are changed or not, if not, i have to set FALSE to skip

**Comment by REJack** [comment]
try my PR :smile: i think you are not the only one who has this problem.

**Comment by amournet** [comment]
yeah!, that's cool, i have just customized your library, it same to you :)
thanks for your reply and your updating :+1:

**Comment by emreakay** [comment]
problem solved thus, closed
