### ISSUE TITLE
"An Error Was Encountered"

### ISSUE THREAD

**Issue by tburks2392** [emreakay/CodeIgniter-Aauth#111]
Hey, trying to implement Aauth and I getting the following error, which I don't understand how, seeing I used the sql provided. 

"You have specified an invalid database connection group (default) in your config/database.php file."

Any idea what this may be and how to fix it?
Thanks for your time and assistance!

**Comment by tburks2392** [comment]
Problem Fixed!!!

**Comment by emreakay** [comment]
closed
