### ISSUE TITLE
user_exist_by_email

### ISSUE THREAD

**Issue by mjmadsen** [emreakay/CodeIgniter-Aauth#114]
user_exist_by_email returns true if the email is available. Based on the name, it should return false.

**Comment by REJack** [comment]
I've tested it with the latest version of Aauth and both functions are equal.
[user_exist_by_name](https://github.com/emreakay/CodeIgniter-Aauth/blob/master/application/libraries/Aauth.php#L1056) [user_exist_by_email](https://github.com/emreakay/CodeIgniter-Aauth/blob/master/application/libraries/Aauth.php#L1074)

Both return true if the name/email is already in the DB.

**Comment by mjmadsen** [comment]
Ah, the wiki makes it sound as though it returns true if it's not found in the db.

**Comment by REJack** [comment]
thx for the hint i fixed it :+1:
