### ISSUE TITLE
groupe hierarchy

### ISSUE THREAD

**Issue by hamzaovic** [emreakay/CodeIgniter-Aauth#115]
how can i use groupe hierarchy?

**Comment by REJack** [comment]
i dont understand your question.

there are the 'Admin' group allowed to any permission.

**Comment by REJack** [comment]
Do you mean like a 'master' group for permissions and other groups can be set the 'master' group as a sub-group to grant the permissions from the 'master' group?

**Comment by hamzaovic** [comment]
yes that's it

**Comment by REJack** [comment]
at the moment Aauth cant handle subgroups, but its a good feature i create a PR for it in the next days.

**Comment by hamzaovic** [comment]
thnx very much

**Comment by przemekn1** [comment]
That feature will be awsome. It will be very helpfull.

**Comment by REJack** [comment]
Guys try #116 pls :smiley: 

i tested all functions no errors found, i hope you like it.

**Comment by hamzaovic** [comment]
thnx very much it's usefull

**Comment by REJack** [comment]
@hamzaovic & @przemekn1 did you test it? :smiley:

**Comment by hamzaovic** [comment]
not yet

2016-04-25 22:04 GMT+01:00 Raphael Jackstadt <notifications@github.com>:
