### ISSUE TITLE
A Database Error Occurred - Table 'healthyb_igni472.pgaauth_users' doesn't exist

### ISSUE THREAD

**Issue by samsoft24** [emreakay/CodeIgniter-Aauth#117]
Hello Team, Got a wierd error which says Table 'healthyb_igni472.pgaauth_users' doesn't exist

A Database Error Occurred

Error Number: 1146

Table 'healthyb_igni472.pgaauth_users' doesn't exist

SELECT * FROM `pgaauth_users` WHERE `email` = 'aa@a.com'

Filename: libraries/Aauth.php

Line Number: 124

**Comment by samsoft24** [comment]
Most likely I may have mistyped something but I cannot figure it out

**Comment by REJack** [comment]
Did you changed the SQL file after the config changes for the tables?

I think you forgot to change the table names (your added prefix `pg`).

**Comment by samsoft24** [comment]
Spot on, it was dbprefix parameter in database.php

	'dbprefix' => 'pg',
