### ISSUE TITLE
loggedin broken?

### ISSUE THREAD

**Issue by Firefly16** [emreakay/CodeIgniter-Aauth#121]
```
public function logout_user(){
        $this->aauth->logout();
        echo $this->aauth->is_loggedin();
        $this->load->view('homepage_view');
    }
```

function loggedin() always return me "1". Should be false here, and when i don't put logout(), it's "1" too !

**Comment by REJack** [comment]
are you still logged in after a reload of the page?

Von meinem iPhone gesendet

**Comment by Firefly16** [comment]
I can't tell because there is no logout table in DB, and is_loggedin always give me 1 :D

**Comment by REJack** [comment]
im at the moment on road, i check it in a hour. 

loggins are not in the database they are stored as cookie or session. 
based on your aauth config. 

Von meinem iPhone gesendet

**Comment by Firefly16** [comment]
No problem. And i didn't touch config except for valid chars :/

**Comment by REJack** [comment]
try to change in your aauth config `use_cookies` to `false` then it uses Sessions.

**Comment by Firefly16** [comment]
Not working

**Comment by REJack** [comment]
if i try it with this 2 little functions :D 
```php
    public function index() {

        $this->aauth->login('admin@example.com', '12345');
    }

    public function logout() {
        $this->aauth->logout();
        print_r($this->aauth->is_loggedin());
    }

```

i get logged out, but the `is_loggedin` after `logout` returns `TRUE` after a page reload it returns `FALSE` i don't know but for me its normal. (it seems PHP still has the session info's in cache or so)


you should check your cookies on login and logout.

by me
__valid cookies__
- on login it creates a `ci_session`-cookie with 2h lifetime

__invalid cookies__

- on logout it changes the `ci_session`-cookie lifetime to now
- on multiple refreshes of `logout` i get many `ci_session`-cookies with page load time as lifetime

**Comment by REJack** [comment]
i found another problem in this checks, with xampp on windows i get no default cookies (only `ci_session`-cookie) even with `use_cookies` is `true` that's need to be reproduced on my web-servers

**Comment by Firefly16** [comment]
I don't really know what u want me to do, but every change i made always give me '1', even with page reload :/

**Comment by REJack** [comment]
I work with Firefox and there is a addon named [Cookie Monster](https://addons.mozilla.org/en-US/firefox/addon/cookie-monster/) with this i can see the created cookies from the login also the changes of the cookie on logout

**Comment by Firefly16** [comment]
name: ci_session
content : 17437bd82acb38cbb455d8d4e68e14a823346b69
host: localhost
path: /
expire: mercredi 4 mai 2016 17:16:14

And when logout: no cookies.

Same for 'use_cookies' in true and false.

**Comment by REJack** [comment]
so your logout works, try this if logout works and `is_loggedin` returns the right result.

```php
public function logout_user(){
        $this->aauth->logout();
        //$this->load->view('homepage_view');
        redirect('<CONTROLLER>/test_loggedin');
}
public function test_loggedin(){
        var_dump($this->aauth->is_loggedin());
}
```

try this, change `<CONTROLLER>` to your controller name :dancer:

**Comment by Firefly16** [comment]
It returns `bool(false)` :)

**Comment by Firefly16** [comment]
but is_loggedin() is supposed to return true or false, here i have nothing for false and 1 for true. So i will need to do var_dump every time?

**Comment by REJack** [comment]
where u have nothing for false? if you try is_loggedin with print_r?

**Comment by Firefly16** [comment]
```
$this->aauth->logout();
echo $this->aauth->is_loggedin();
```

But in fact, i thing i know where is the probleme. When i do is_loggedin(), it work when i'm logged, but when i logout, it print what is inside the `if($this->aauth->is_loggedin())` and when i F5, the logout work.

**Comment by Firefly16** [comment]
In fact this is my fault i think, because when i loggout people, i send them to the "http://localhost/codeigniter-3.0.6/index.php/login/loggout" and they still be there after clicking. In fact i wanted to let people and the page they are consulting but just whitout beeing logged. But anyway, i will redirect them to the homepage, and it work :)
