### ISSUE TITLE
Where in application do you set the permission sets?

### ISSUE THREAD

**Issue by paulcanning** [emreakay/CodeIgniter-Aauth#123]
I am creating a small bespoke CMS that will have an admin and then users that will belong to different groups.

I imagine I will need to create some basic permissions initially such as "can_create_post" and "can_edit_post".

How should I create these permissions initially? Should I have a "setup" controller?

I don't imagine they can be created dynamically with a CRUD system, as the actual permissions need to be coded into the controllers?

**Comment by REJack** [comment]
For this case i have a __Installer__-Controller that initializes Database Tables (not only Aauth's), Default Users, additional Groups, additional Permissions & some other stuff.

You can manage this easily with CI's [Migrations Class](https://codeigniter.com/user_guide/libraries/migration.html).

**Comment by paulcanning** [comment]
Ah, good idea! Still trying to wrap my head round how I'm going to implement the permissions. I need to make it as dynamic as possible
