### ISSUE TITLE
Suggestion - Do not expose User ID in reset password link

### ISSUE THREAD

**Issue by paulcanning** [emreakay/CodeIgniter-Aauth#124]
It seems like a bit of a security risk including the users ID in the reset link.

You are using a unique verification code, which is more then enough to locate the users record in the database.

My suggestion is to remove the user ID and use the verification code on it's own.

**Comment by REJack** [comment]
That's a good idea i create in the next days a PR for this.

**Comment by Firefly16** [comment]
I'm new in github but, for hint, don't we have to use the "pull requests" section?

**Comment by REJack** [comment]
anybody can use the PR here, anyone can contribute to this Project.

**Comment by REJack** [comment]
check this commit too :smiley:
