### ISSUE TITLE
valid_chars - regex?

### ISSUE THREAD

**Issue by paulcanning** [emreakay/CodeIgniter-Aauth#125]
The `valid_chars` setting in the config file has an empty array by default, allowing for all characters.

If I want to limit the characters to just A-Z, do I need to have the array like `array('a', 'b', 'c', ...)` or can I use regex, like `array('[A-Z]')` ?

**Comment by REJack** [comment]
The `valid_chars` with an empty array allows all alphanumeric characters. only if you want to use other chars like `.`, `,`, `-` add them in the `valid_chars`-array.

> Valid chars for username. Non alphanumeric characters that are allowed by default [Config Line 41](https://github.com/emreakay/CodeIgniter-Aauth/blob/master/application/config/aauth.php#L41)

**Comment by paulcanning** [comment]
May I suggest renaming it to `additional_valid_chars` or perhaps explaining a bit better in the docs?

**Comment by REJack** [comment]
renaming is a good idea, i change that in my PR
