### ISSUE TITLE
Suggestion - Add BCrypt support

### ISSUE THREAD

**Issue by paulcanning** [emreakay/CodeIgniter-Aauth#126]
As the title. I usually use the ion_auth library, but it does not have any ACL support. But it does offer BCrypt support for PHP 5.5 =>.

Please look at including BCrypt support for this library :)

**Comment by REJack** [comment]
That's a good idea i create in the next few days a PR for this.

**Comment by REJack** [comment]
i added BCrypt/password_hash() with e4aa1f5bc71a3de5db73309ec31b8bc7a8e287f8.

**Comment by paulcanning** [comment]
In the new config, what should the following options be set to for BCRYPT usage?

```
 'hash'                           => 'sha256',
 'use_password_hash'              => false,
 'password_hash_algo'             => PASSWORD_DEFAULT,
 'password_hash_options'          => array(),
```

**Comment by REJack** [comment]
only `use_password_hash` to `true`

at the moment BCrypt is the only hash_algorithm so `PASSWORD_DEFAULT` is the same as `PASSWORD_BCRYPT`
`password_hash_options` not needed, but it can used to increase cost or set a own salt

**Comment by REJack** [comment]
and use the BCrypt sql file :smile:

**Comment by paulcanning** [comment]
Hmm, mines working ok without BCRYPT SQL file.... What's the difference?

Can you look at improving the wiki?

**Comment by REJack** [comment]
if you updated the password it works :D 

its not a real different in the sql files except pass is in bcrypt `varchar(60)`, in default its `varchar(64)`

i improved user functions already, later i improve the pm section, do you know any other section they need to improved too? 
for 2.5.0 i doesn't add GitBook Documentation
