### ISSUE TITLE
Public group makes no sense

### ISSUE THREAD

**Issue by paulcanning** [emreakay/CodeIgniter-Aauth#127]
The docs say the public group is for people not logged in.

If there are not logged in, how can you get the group info?

To test this, I added some basic code to a controller:

`var_dump($this->aauth->get_user_groups());`

If you visit the controller when not logged in, it shows an empty array. Surely, according to the docs, it should show the public group?

**Comment by REJack** [comment]
yeah guests doesn't have any user_group assigned.

permissions assigned to public group can be checked over `is_allowed(<perm name/id>)`.

**Comment by paulcanning** [comment]
Might be worth explaining this more in-depth? And/or provide a good example of it in use?

**Comment by REJack** [comment]
you can assign a permission to `public`-group with `$this->aauth->allow_group('public', '<YOUR PERM NAME>');`

you can check it over `$this->aauth->is_allowed('<YOUR PERM NAME>')` and `$this->aauth->is_group_allowed('<YOUR PERM NAME>')`.

PHP example: `redirect if not allowed`
```php
  if( !$this->aauth->is_allowed('<YOUR PERM NAME>')){
    redirect('/');
  }
```

for example: you can create a perm named `register` for the register site and place the example PHP in the register controller, then public's could not register and other groups too except admins.
if you want to allow public's register you need only assign the `register`-perm to the public group.

Hint: if public users has access then registered users has access too

**Comment by REJack** [comment]
i change the `get_user_groups()` function, that it returns the public group if user isn't logged-in/registered.
