### ISSUE TITLE
System var usage?

### ISSUE THREAD

**Issue by paulcanning** [emreakay/CodeIgniter-Aauth#128]
What's the use case for the system_vars?

Are they meant to act like system wide options? Example, make all text red, or make the background pink?

If so, why is such a thing in this library? This is an auth library, and system wide options can be done easily enough :/

Seems redundant.

**Comment by REJack** [comment]
i know ^^ i think the same

**Comment by paulcanning** [comment]
Maybe remove this in favour of implementing a better way to store user "profiles" (mentioned in a previous issue) ?

**Comment by REJack** [comment]
Which issue you mean, #64? 

set_user_var/get_user_var is a good way to store profile data.
it's fast (see https://github.com/emreakay/CodeIgniter-Aauth/issues/72#issuecomment-162523200) & individually trough self-defined key's no annoying DB changes.

**Comment by paulcanning** [comment]
No, I meant the system vars. User vars are correct.

**Comment by paulcanning** [comment]
Oh sorry, if you mean my comment about storing user vars, then only if possible. Current implementation is good.

**Comment by REJack** [comment]
which comment you mean, i cant find it :smile:?

**Comment by paulcanning** [comment]
> Maybe remove this in favour of implementing a better way to store user "profiles" (mentioned in a previous issue) ?

**Comment by REJack** [comment]
this i saw but if you write "mentioned in a previous issue" which issue you mean?

**Comment by paulcanning** [comment]
Sorry, I just meant that comment in this issue :) Ignore me :P

**Comment by REJack** [comment]
oh ok :D

**Comment by REJack** [comment]
removed System Variables with bfdc6ea1deab807653fa8254b35dd0049b16a1ed
