### ISSUE TITLE
Single method to get all user variables for specific user?

### ISSUE THREAD

**Issue by paulcanning** [emreakay/CodeIgniter-Aauth#129]
Rather then having to know the variable keys and get them individually, can you look at a single method to fetch all variables for a given user?

Obviously you can still get individual variables, but being able to get an object with all of then in would be great.

**Comment by REJack** [comment]
`list_user_var_keys($user_id)` 
Return array of variable keys or FALSE

**Comment by paulcanning** [comment]
Hmm, I meant more like returning the keys and values. Also, this method is not in the documentation :|

**Comment by REJack** [comment]
i work at the moment on a complete new docs. 

i create later a function for this. 

Von meinem iPhone gesendet

**Comment by REJack** [comment]
try my PR/Fork :smile:

**Comment by paulcanning** [comment]
Any idea if your PR's can be put into the main repo yet?

**Comment by REJack** [comment]
i'll contact emre that he merge it in the next days. 

Von meinem iPhone gesendet

**Comment by REJack** [comment]
i created a release with this enhancement [v2.4.7](https://github.com/emreakay/CodeIgniter-Aauth/releases/tag/v2.4.7)
