### ISSUE TITLE
update_user with only one changing parameter

### ISSUE THREAD

**Issue by Firefly16** [emreakay/CodeIgniter-Aauth#130]
Hi,

update_user function, when i just change name or email, it say: 

- Email address already exists on the system. Please enter a different email address
- Username already exists on the system. Please enter a different username.

Is there a way to just change one of thoses two info without changing the second? :)

**Comment by REJack** [comment]
`update_user($user_id, FALSE, FALSE, $name)` changes only name
`update_user($user_id, $email, FALSE, FALSE)` changes only email

**Comment by Firefly16** [comment]
Ho, ok, thx!
