### ISSUE TITLE
TOTP Google Authenticator

### ISSUE THREAD

**Issue by paulcanning** [emreakay/CodeIgniter-Aauth#131]
Can someone please include documentation on how to use the TOTP options?

There is **ZERO** documentation on how to use this.

**Comment by paulcanning** [comment]
Just to add to this, it looks like the method `generate_unique_totp_secret` isn't even used in the library. I have the strong feeling the whole TOTP feature isn't complete?!

**Comment by REJack** [comment]
the TOTP is complete and works the Documentation over the GitHub Wiki is obsolete. I work at the Moment on a better docs.

**Comment by REJack** [comment]
Here some little information about the TOP Feature

there are 3 functions for TOTP
 - `update_user_totp_secret($user_id/FALSE, $secret)`
 - `generate_unique_totp_secret()`
 - `generate_totp_qrcode($secret)`

First you need to generate a secret
```php
$secret = $this->aauth->generate_unique_totp_secret();
```
Then you can display the QR-Code for Mobile Phones
```php
echo generate_totp_qrcode($secret);
```
After this you can update the users secret
```php
$this->aauth->update_user_totp_secret(FALSE, $secret);
```

**Comment by paulcanning** [comment]
Then what do you do after a secret is set for a user? How is it used in the login process?

**Comment by REJack** [comment]
sry i forgot that :D

it get passed with the login function 
`login($identifier, $pass, $remember, $totp_code)`

**Comment by paulcanning** [comment]
So you need to have an input field for the user to enter the `totp_code` ?

I thought the point of TOTP was to login in just using a code, not an identifier, password AND topt code...

**Comment by REJack** [comment]
yes u need a 3rd/4th input for the totp_code.

but there are many pages with a totp that used with identifier, password AND topt code, github has first identifier and password then they ask for a totp code.

i want to add a way to confirm with totp after login like github it.

**Comment by REJack** [comment]
i added a way to confirm with totp after login like github has it. 

tested, tomorrow i add a little tutorial/docs for it and the other way :smile:
