### ISSUE TITLE
reCAPTCHA not working in CI3 following Wiki

### ISSUE THREAD

**Issue by paulcanning** [emreakay/CodeIgniter-Aauth#132]
I have set the config variables, and put `echo $this->aauth->generate_recaptcha_field();` in my view.

No reCAPTCHA is shown.

Looking at the library, you are checking for the `reCAPTCHA` cookie, but the config needs cookies to be set to false for CI3.

Meaning reCAPTCHA cannot be used in CI3...

**Comment by paulcanning** [comment]
Argh, this simply makes no sense. The reCAPTCHA generator code check for the `reCAPTCHA` cookie, which seems to only be set when you actually login.

Seriously, this is ridiculous.

**Comment by REJack** [comment]
`echo $this->aauth->generate_recaptcha_field();` shows only the reCAPTCHA, if you had more login attempts than `recaptcha_login_attempts` in your config.

**Comment by paulcanning** [comment]
I set it to 0, it doesn't show.

I set it to 1, tried to login in with wrong details several times, it doesn't show.

**Comment by REJack** [comment]
`ddos_protection` is true in config?

**Comment by paulcanning** [comment]
My config

```
$config_aauth["default"] = array(
	'no_permission'                  => FALSE,

	'admin_group'                    => 'admin',
	'default_group'                  => 'default',
	'public_group'                   => 'public',

	'db_profile'                     => 'default',

	'users'                          => 'aauth_users',
	'groups'                         => 'aauth_groups',
	'user_to_group'                  => 'aauth_user_to_group',
	'perms'                          => 'aauth_perms',
	'perm_to_group'                  => 'aauth_perm_to_group',
	'perm_to_user'                   => 'aauth_perm_to_user',
	'pms'                            => 'aauth_pms',
	'system_variables'               => 'aauth_system_variables',
	'user_variables'                 => 'aauth_user_variables',

	'remember'                       => ' +3 days',

	'max'                            => 13,
	'min'                            => 5,

	'valid_chars'                    => array(),

	'ddos_protection'                => true,

	'recaptcha_active'               => true,
	'recaptcha_login_attempts'       => 1,
	'recaptcha_siteKey'              => '',
	'recaptcha_secret'               => '',

	'totp_active'                    => false,
	'totp_only_on_ip_change'         => false,
	'totp_reset_over_reset_password' => false,

	'max_login_attempt'              => 10,

	'login_with_name'                => false,

	'use_cookies'                    => false,

	'email'                          => '',
	'name'                           => '',

	'verification'                   => true,
	'verification_link'              => '/verify/',
	'reset_password_link'            => '/reset-password/',

	'hash'							 =>	'sha256'
);
```

**Comment by paulcanning** [comment]
Seems `login_attempts` in the DB is not being incremented for some reason.

**Comment by paulcanning** [comment]
Right, there are some major flaws with this library. `login_attempt` only gets incremented if you tried to log into an account with the correct email/username and a WRONG password that is .>= or <= the minimum/maximum length allowed.

Example:

password min/max length is set to 5/13

If I login with a real email, but I enter a password such as `test` this will not trigger a login_attempt.

Also, the shear fact you are counting on people entering a real email/username to show the reCAPTCHA, rather then show it with login attempts with non-existent emails/usernames is ridiculous.

**Comment by REJack** [comment]
i know the ddos protection is not so good, 
it doesnt work with non-existent emails/usernames or invalid passwords(to short/long).

i have some ideas to change it and the reCAPTCHA, i add some commits for this in my PR tomorrow.

**Comment by paulcanning** [comment]
Despite the issues with the DDOS protection and login attempts etc, the reCAPTCHA does seem to be working now. I'll close this issue.
