### ISSUE TITLE
Fatal flaw with `update_login_attempts`

### ISSUE THREAD

**Issue by paulcanning** [emreakay/CodeIgniter-Aauth#133]
This method is supposed to check the last login attempt with the current time, and according to the wiki, limit the login attempts each **MINUTE**.

However, the check is done using `date("Y-m-d- H:0:0")` which means only the hour is checked. not the minute.

It should be `date("Y-m-d- H:i:0")`

EDIT - If it is supposed to be attempts per hour, for the love of all things holy, update the documentation!

**Comment by REJack** [comment]
i know that's get changed tomorrow too.

**Comment by REJack** [comment]
check out my commit referenced to this issue :smile:
it is ok, for now? 

I'll create a new issue for a non-user based ddos check.for an ip ban and not user ban.

**Comment by paulcanning** [comment]
I think you made a mistake. 

Aauth.php, line 643. You can't just pass an integer into `strtotime()`

You surely just need to check the last login attempt time with the current time? 

Also, in what circumstances would you not want to update the last login time? Seems like a nonsense config option.

**Comment by REJack** [comment]
oh that i missed changed in e205dc2

its not nonsense, if you would brute force a aauth page with a special script that reacts every 25 seconds or so it would be banned but if the script reacts every 35 seconds he would never be banned. with the config var active every try would be noticed unless he waits full 5 minutes the login_attempts get reset. (based on `max_login_attempt` = 10 and `max_login_attempt_per_minutes` = 5)

**Comment by REJack** [comment]
sometimes you need to think like a hacker, then you can better secure your page

**Comment by paulcanning** [comment]
What I mean is, why would you not update the last login time? 

Your new config option update_last_login_attempt is set to false by default. 

In what example would you have this set to true? 

Surely you want to update the login attempt time everytime? So it should always be true? 

Either way, the issue with your strtotime comparison is still wrong.

**Comment by REJack** [comment]
1. the commits are in the develop branch
2. function not tested 100% so i leave the default config vars. i change it later to true after tests
3. i found the failure with strtotime :smile:

**Comment by REJack** [comment]
look at e4aa1f5

**Comment by REJack** [comment]
sry waffle.io closed it ^^ i moved it to done

**Comment by REJack** [comment]
did you tested my last fix for it?

**Comment by paulcanning** [comment]
I can't test till Monday. 

Still trying to understand why update_last_login_attempt is an config option though?! 

Can you provide a clear example for when you would have the option set to false?

**Comment by REJack** [comment]
oh that you mean, yeah i can remove it its better anyway to update the time on every login attempt and i can remove some more lines :smile:

**Comment by REJack** [comment]
i changed it, i hope it works like charm if you test it :smile:

**Comment by REJack** [comment]
i changed `max_login_attempt_per_minutes` to `max_login_attempt_time_period` too.

**Comment by paulcanning** [comment]
Might need to include something in the docs to explain what syntax can be used for that option. Strtotime is pretty smart but I think it can get confused. Especially if people try to use their native language for the words "minutes", "hours" etc?

**Comment by REJack** [comment]
i work partially on new docs, at the moment only local but i commit it in few days a prerelease of it.
