### ISSUE TITLE
Our new Collaborator :D

### ISSUE THREAD

**Issue by emreakay** [emreakay/CodeIgniter-Aauth#134]
Hi everyone;

I'm sorry about merging PRs a little bit late because of my busy jobs. To solve this problem I added @REJack as collabrator of Aauth.

I'm sure he will improve Aauth and step it forward.

Congratulation @REJack  :+1:

**Comment by REJack** [comment]
@emreakay thx i will add in few days complete new docs

**Comment by Firefly16** [comment]
Ho, I thought REJack was the guy who carried the nickname of emreakay and was using his personnal "REJack" account to answer people :D 

He does a great job, he deserve it ! Congrat :tada:

**Comment by REJack** [comment]
no ^^ i use Aauth in my jobs and i love it, so i started contributing with the Language Support since Aug 2014 :smile:

**Comment by emreakay** [comment]
@Firefly16 @REJack is our second author :D

**Comment by paulcanning** [comment]
Great news. I know I've pestered the heck out of @REJack in the last few days and he has responded quickly.

This is a great library and I really want it to improve in the few areas its not 100%

**Comment by REJack** [comment]
i close this issue :smile: its not necessary.
