### ISSUE TITLE
id groups and members

### ISSUE THREAD

**Issue by Firefly16** [emreakay/CodeIgniter-Aauth#135]
To celebrate your contributor title... an issue ! :smile: 

When i add new groups and members, the id continue with the last id added. So, if we had 1,2,3 and we delete 2 and 3, the next one will be 4. Is it possible to fill the DB with the ID not used? to do 1,2 again instead of 1,4 ?

**Comment by REJack** [comment]
yep that's default by the MySQLs Auto-Incremental ID.
with aauth you cant change it, its only possible with phpMyAdmin etc.

**Comment by REJack** [comment]
if you change the user id, you need to update the user password.

**Comment by paulcanning** [comment]
Yea, it's really not an issue. If you really wanted, you could maybe reset the AUTO_INCREMENT ID, but you are going to get yourself into a right mess.

And as @REJack states, the password is salted with the users ID (maybe not the _best_ way to salt a password, but hey, it is what it is!)

**Comment by REJack** [comment]
best way is edit the SQL file before upload/import it, 
i'm working on that aauth creates the db automatically incl changed groups.

@paulcanning yeah the hashing is not perfect, i don't know what we could use instead of userID (its a not changeable unique variable for every user)

**Comment by paulcanning** [comment]
Do you need a salt for the BCRYPT work? If so, maybe take a look at the ion_auth library for inspiration?

**Comment by Firefly16** [comment]
For the user its not a real problem but, for groups and perms, i created a control panel to add or delete one, and display them. If the increment do not follow 1,2,3,4, etc, it will not be user friendly for other people who will manage groups. I'm in auto-increment, i don't really now what to change (phpmyadmin). And you say that changing id need to change password too. But if i just change mannually groups and perms (and perms allow for groups), i imagine this is ok (i dont give perms to user, only to groups).

**Comment by REJack** [comment]
if you change PermID's you need to change them in perm_to_group too.
if you change GroupID's you need to change them in user_to_group, perm_to_group too.

**Comment by paulcanning** [comment]
Users who manage groups etc don't really need to see the ID. Use the group name to be "friendly".

**Comment by REJack** [comment]
@paulcanning for BCrypt not but its work only on `PHP 5 >= 5.5.0 & PHP 7` so i cant switch it with the actual hashing method only as extra option over config and a special SQL file.

yeah with group_name its easier for manage groups/perms, the id is only important for the assignment on name changes etc. but its not really a good idea if the perms are hardcoded in PHP

**Comment by Firefly16** [comment]
Ok, i think i will use the name, say to me when i can close this 'issue' :P

**Comment by REJack** [comment]
now i can close it too :smiley:

**Comment by Firefly16** [comment]
So much power in you ! :D

**Comment by paulcanning** [comment]
FYI @Firefly16 you can close your own issues too
