### ISSUE TITLE
Aauth and TTFB (Time to First Byte)

### ISSUE THREAD

**Issue by AzrielOmega** [emreakay/CodeIgniter-Aauth#136]
Hello everyone, I'm new to Codeigniter Auth System and I choose Aauth as one of the options, but I have a problem with website load time.

Before that, my TTFB is about 1.4s (I'm not so proud of it) and after install Aauth, my TTFB goes to 2.5s (nearly double). The real problem is when I use any Ajax function, that took merely 2-3 second to complete the task, and I feel very bad about it.

So, anyone notice this problem and how can we solve it ?

**Comment by AzrielOmega** [comment]
And sorry if my presentation is clumsy because English is not my native language.

**Comment by REJack** [comment]
It would be helpful if you give me some more infos: PHP version, MySQL version, TTFB from simple phpinfo(). 

How you test your TTFB, trough PHP or a Browser Dev Tool?

is your TTFB only with loaded aauth library or with operations too like get_user() etc.

**Comment by REJack** [comment]
I use PHP 5.5.9 and MySQL 5.5.

I tested my Page with [bytecheck.com](http://www.bytecheck.com/),
 - aauth's example controller takes 0.350 seconds on average.
 - CI3's Welcome Controller takes 0.350 seconds on average.
 - simple phpinfo() takes 0.450 seconds on average.

With my Firefox it takes 0.150 seconds on average on any page 
(Internet-Speed 200mb/s & ISP's DSL exchange is 4 houses away average ping 7ms :smile: best life ever).

I think its your Web-Server not Aauth try my links and send me the averages.
 - [Aauth Example Controller](https://ws.rejack.us/Aauth-Test/index.php/example)
 - [CI3 Welcome Controller](https://ws.rejack.us/Aauth-Test/)
 - [simple phpinfo()](https://ws.rejack.us/info.php)

**Comment by AzrielOmega** [comment]
First of all, many thanks for @REJack for your valuable and helpful advice. Problem solved.

Today I tried many things to improve TTFB but when I'm just include the Aauth library, the waiting time auto increase to 3-4 second.

Then I tried to make a fresh install with CodeIgniter 3.0.6. Everything went fine until I load 'database' library, the TTFB suddenly go up to 1 second. And when I include Aauth, it still went to 3-4 seconds.

Luckily, after I read @REJack comment, I just noticed that I haven't updated XAMPP since Codeigniter 3 released (It's my first CI3 project and still on localhost).

So I upgrade XAMPP from PHP 5.4 to 5.6 and ... BOOM. The webpage speed when completely from a bicycle to a rocket ship.

Conclusion: CodeIgniter 3: good, Aauth: very good, @AzrielOmega: not so good, @REJack: SUUUUPER...

**Comment by REJack** [comment]
@AzrielOmega no problem :smile: PHP7 could be faster than PHP5.6 but i doesn't tested it :D use PHP5.5 & PHP5.6 in my Projects and own Sites.

I'll close this issue, if you have some other questions or suggestions feel free to open a new issue.
