### ISSUE TITLE
MySQL 5.7.9 : PRIMARY KEY must be NOT NULL

### ISSUE THREAD

**Issue by jonathanBieler** [emreakay/CodeIgniter-Aauth#139]
I'm getting this when running `Aauth_v2.sql` :

    CREATE TABLE `aauth_perm_to_group` (
      `perm_id` int(11) unsigned DEFAULT NULL,
      `group_id` int(11) unsigned DEFAULT NULL,
      PRIMARY KEY (`perm_id`,`group_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8
    MySQL said: Documentation

    #1171 - All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead

It seems that this is not allow since v.5.7.3. Removing the `DEFAULT NULL` seems to fix the issue.

**Comment by REJack** [comment]
thx for the hint, i check this later :+1:

**Comment by REJack** [comment]
i fixed the SQL files with 36da952709e023cd203150121abaffbe5bee4a00

release comes in few days

**Comment by jonathanBieler** [comment]
Great thanks.
