### ISSUE TITLE
PM improvements

### ISSUE THREAD

**Issue by paulcanning** [emreakay/CodeIgniter-Aauth#145]
Can you please look at making PMs a bit more secure?

Please expand `get_pm()` to accept a user ID.

**Comment by REJack** [comment]
User ID for `get_pm()` is a good idea.

The whole PM system needs to be improved, my ideas are:
 - multiple receivers
 - outbox function
 - encrypted messages & titles

**Comment by paulcanning** [comment]
Outbox can be done with current code.

Multiple receivers sounds good.

Just needs sprucing up a bit

**Comment by REJack** [comment]
a simple Outbox yes, but senders cant remove a pm from their list without delete the whole pm.

I start tomorrow with the first changes, v2.5.0 will be a big release :smiley:.

**Comment by REJack** [comment]
i added the first enhancement: 483ed60540019d95c9bb2f24b447c8b79f26919e

> enhanced `get_pm()`
>  - added `$user_id` argument between `$pm_id ` & `$set_as_true`
>  - changed `set_as_true` to set read date only if user_id is equal to receiver's id

**Comment by REJack** [comment]
i added pm_encryption & send_pms() for multiple receivers, with these commits: 
30239ed3a0945db05c10ce43e2ab9d2ef7641741, 1f1afbde0abf79594b4eb0351e645ca8cd6f42cd & e6e770a95d5c0f10e26226aaae6b8e308e60eeab


`send_pms()` returns a array of receiver user ids with specific error message on failure or TRUE if message successfully sent

here is a var_dump of send_pms with 3 receivers
```php
array(3) {
  [1]=>
  string(49) "It is not possible to send a Message to yourself."
  [2]=>
  bool(true)
  [3]=>
  string(19) "User does not exist"
}

```
tell me what you think about it, next i change `delete_pm()` & `list_pms` to give the sender a choice to remove a message from outbox.

**Comment by REJack** [comment]
i added some enhancements with fe89cdb861d6864dc200db4089561669a3fd4353.

>  - fixed explanation info text in aauth config 
>  - added `pm_cleanup_max_age`-config_var
>  - added 2 fields (`pm_deleted_sender` & `pm_deleted_receiver`) in pms table
>  - changed `list_pms()` to catch only not deleted pm's
>  - changed `delete_pm()` now it need a user_id to delete a pm (like `get_pm()`)
>  - changed `delete_pm()` sender's can now detete pm's from outbox
>  - changed `count_unread_pms()` it counts now only not deleted pm's.
>  - added `cleanup_pms()` removes pms older than X defined by `pm_cleanup_max_age`-config_var

**Comment by paulcanning** [comment]
Is there any form of new release yet ?

**Comment by REJack** [comment]
i've added a new Pre-Release [v2.5.0-alpha.5](https://github.com/emreakay/CodeIgniter-Aauth/releases/tag/v2.5.0-alpha.5)

I test this evening if anything works correct and then its ready to get released ^^

**Comment by paulcanning** [comment]
Ok, I can wait till it's tested. Got other stuff to work on in the mean time :)

**Comment by paulcanning** [comment]
Another possible improvement - allow the "system" to be the sender of the PM. Currently you have to supply a sender ID, and whilst I can use ID 1, which happens to be the admin, it'd be nice if you didn't need to supply an ID and therefore the PM is being sent on behalf of the application.

Thoughts?

Also, did you test the new release?

**Comment by REJack** [comment]
Nice Idea.

Like a System News PM's or so? 
we could add ability to supply sender_id as`false` and fill it in db with 0.

> Also, did you test the new release?

No i have started with it since 10-20 minutes, i created a new test environment on my root for it :smile:

**Comment by REJack** [comment]
tests done!
I added your new improvement idea :smile: 
`send_pm(FALSE,1,'test','test message')` would send to your admin a PM from System :smile: 

[v2.5.0-alpha.6](https://github.com/emreakay/CodeIgniter-Aauth/releases/tag/v2.5.0-alpha.6)

**Comment by paulcanning** [comment]
Nice.

When can we see a proper release?

**Comment by REJack** [comment]
the release is live

**Comment by paulcanning** [comment]
With PM encryption, how do I show the decrypted title and message?

**Comment by REJack** [comment]
it get decrypt on `get_pm()` see [L2034](https://github.com/emreakay/CodeIgniter-Aauth/blob/master/application/libraries/Aauth.php#L2034)

**Comment by paulcanning** [comment]
It's broken in CI3 then. It isn't decrypting the title.

I have noticed though, the SQL query for getting a PM is terrible.

Currently you are getting by PM ID and either the receiver or sender ID being the passed user ID. This is wrong!

The query should simply be get by PM AND receiver being user ID..

Currently it gives the wrong results.

**Comment by paulcanning** [comment]
OK, so, the title is NOT being decrypted with `list_pms()`

**Comment by REJack** [comment]
i doesnt noticed any error like this. if a  pm isnt encrypted and you decrypt it, its empty. 

i check this in 30 mins. 

Von meinem iPhone gesendet

**Comment by paulcanning** [comment]
i'll do a PR

**Comment by REJack** [comment]
Thats not wrong, if we pass only the receiver ID, and a sender take a look over his send PM he set the read date for the PM so its not wrong and it works. i get no error.

> Currently you are getting by PM ID and either the receiver or sender ID being the passed user ID. This is wrong!

> The query should simply be get by PM AND receiver being user ID..

**Comment by REJack** [comment]
oh ok i see now the error i took a print_r  
but we need to pass receiver or sender ID.

**Comment by REJack** [comment]
i missed `group_start()` & `group_end()` :dizzy_face:

**Comment by paulcanning** [comment]
It may be better to have two parameters then. using a single parameter that could be two different IDs is not a good idea.

**Comment by REJack** [comment]
it should be 

```php
		$query = $this->aauth_db->group_start();
		$query = $this->aauth_db->where('receiver_id', $user_id);
		$query = $this->aauth_db->or_where('sender_id', $user_id);
		$query = $this->aauth_db->group_end();
```

then it works right

**Comment by REJack** [comment]
i dont think so with two parameters. its not needed MySQL or SQL is perfect for this

**Comment by REJack** [comment]
i would let it empty in a PM Center for a User to catch the logged in user, so a another user cant catch the pm.
i would only use it for an admin center with a specific user ID.

**Comment by REJack** [comment]
i released the fixes try it
