### ISSUE TITLE
There is no way to sort users by "date created"

### ISSUE THREAD

**Issue by webstone-ro** [emreakay/CodeIgniter-Aauth#146]
I just realized today that there is no date_created or date_added type of field in the aauth_users table. If you need, for example, an admin dashboard list of users that shows them in the order they created their accounts, you can't do that right now, correct? Am I missing something or is there absolutely no way to see "new users" right now?

**Comment by REJack** [comment]
there is absolutely no way to see "new users" right now.

i will add this feature to the develop branch.

**Comment by REJack** [comment]
added this enhancement with 10e844653eb28dfcefa0c6aa6aa9909fd1625b6d
