### ISSUE TITLE
Inconsistency documentation for 'create_user'

### ISSUE THREAD

**Issue by stupidoes** [emreakay/CodeIgniter-Aauth#147]
HI all... 

I'm currently try to implement this library for my backend project and would happy to contribute .. :)

Anyway, when i tried to implement by following the documentation ( 2-Installation-and-Configuration ), think there's something wrong. The docs said,

 ```
public function create_user() {
        if ( $this->aauth->create_user('ali@ali.com','pasword','Mr Ali') ){
             echo 'OK. Succesful register';
        } else {
            echo 'Please fix the issues below';
            echo $this->aauth->print_errors();
        }            
    }
```
but the default configuration for "additional_valid_chars" is empty, so that _empty space_ is not allowed. And then i faced with an error. I got it running by adding _empty space_ to config.

I don't know whether this is the default and correct behavior. Why should name only in alphanumeric ?

NB : Sorry for my english :)

**Comment by REJack** [comment]
I know the docs are outdated, i work on it :smile: .
The name is default only alphanumeric, because i doesn't want to decide for the users, if they want use mail or name for login. if users want to use name for login alphanumeric is important for it. 

I personally use the user's name not for first/last name, its only a display name or nickname in my projects. I use for the first/last name the user vars functions.

**Comment by stupidoes** [comment]
Oh i see~~ 

So $name on was actually user selected _login username_ rather that real user's Last/First name.. I thought it was user Full Name since i obediently following the manual... I'll keep that in mind.. :)

**Comment by REJack** [comment]
I will add some example configs in the next release

**Comment by paulcanning** [comment]
Name should really be changed to username I guess, much easier for people to understand.

**Comment by REJack** [comment]
good idea i change it later ^^

**Comment by REJack** [comment]
`name` changed to `username` in [v2.5.0-alpha.6](https://github.com/emreakay/CodeIgniter-Aauth/releases/tag/v2.5.0-alpha.6)
