### ISSUE TITLE
user_exist_by_name 

### ISSUE THREAD

**Issue by salain** [emreakay/CodeIgniter-Aauth#149]
Hi, 
Great work on the update. 
Just an error on line 1101 in method user_exist_by_name the return statement should be change to
$this->user_exist_by_username($name)

**Comment by REJack** [comment]
:dizzy_face: thx i fix it fast

**Comment by REJack** [comment]
fix is released with [v2.5.2](https://github.com/emreakay/CodeIgniter-Aauth/releases/tag/v2.5.2)
