### ISSUE TITLE
Send Aauth errors to form errors?

### ISSUE THREAD

**Issue by paulcanning** [emreakay/CodeIgniter-Aauth#152]
Is there a way to send the aauth errors (when logging in for example) to the CI form errors?

In CI, you can either echo out `validation_errors()` to show all errors, or individually with `form_error()`.

Aauth errors would fit in much nicer if included with these somehow?

Right now, I am showing form errors individually, as I am using Bootstrap and its styling guide. But any errors that crop up from Aauth, with as a user not existing, or a password being wrong, my only option is to have these printed out separately.

**Comment by REJack** [comment]
At the moment this doesn't work with Aauth, but i take this into my v3.0.0 plans.

**Comment by paulcanning** [comment]
I have a workaround for now :) Looking forward to v3!
