### ISSUE TITLE
mail

### ISSUE THREAD

**Issue by Firefly16** [emreakay/CodeIgniter-Aauth#153]
Hi, i'm in localhost, and i can't mail, first i had error with port 25, but i tried putting in php.ini: 

[mail function]
; For Win32 only.
; http://php.net/smtp
SMTP=smtp.gmail.com
; http://php.net/smtp-port
smtp_port=465

I tried to put `$config['smtp_crypto'] = 'tls'; $config['smtp_port'] = '465';` too.

But after i had "Message: mail(): SMTP server response: 530 5.7.0 Must issue a STARTTLS command first. lr9sm27878626wjb.39 - gsmtp"

So i decide to delete all modifications and ask you if there is some things to change in aauth config to allow mails? 

This is for the confirmation mail.

**Comment by REJack** [comment]
1. NEVER change in your php.ini the SMTP Server, can break other pages on Production Servers
2. Aauth doesnt use E-Mail configs, i add this as a config var
3. the Error message said you need a STARTTLS command first, this means you need a login to use this SMTP server.

At the moment Aauth use only CI's Email Library with php's mail() function.

**Comment by REJack** [comment]
added release [v2.5.6](https://github.com/emreakay/CodeIgniter-Aauth/releases/tag/v2.5.6) with this enhancement.

i tested it and it works :smile: 

My email_config:
```php
 'email_config'                => array(
                                        'protocol' => 'smtp',
                                        'smtp_host' => '>MY HOST<',
                                        'smtp_user' => '>MY MAIL<',
                                        'smtp_pass' => '>MY PW<',
                                        ),
```

**Comment by Firefly16** [comment]
When u say, to login, u mean, login on aauth or login on our mail like gmail? Because we give our email, so normally its good.

And for the 1, a lot of people say on internet to change smtp and port on the php.ini ^^'

**Comment by Firefly16** [comment]
Where did you get 'email_config' ? I only have my 'email' on system/libraries :o

**Comment by Firefly16** [comment]
But for now i use `$mail = new PHPMailer();` seems to work, i juste hope the CI form rules are enough for security ^^

**Comment by REJack** [comment]
SMTP Servers need a login to Auth, otherwise anybody could use your mail name to send spams, etc.
i added `email_config` in Aauth's Config.
php.ini changes in Develop Server are ok, but on production its not good, i have 10domains on my private server if i change the php.ini any get the change. Some Hoster doesnt allow to modify php.ini or restrict it to memory_limit & upload limits (post_max_size & upload_max_filesize).

Try my enhancement you should not need PHPMailer.

**Comment by Firefly16** [comment]
That's weird, when i sign up on websites, i dont need to be logged, or i dont understand what u mean by logged. U mean logged like, on gmail etc? Or smtp server is something different than the usual mail system usually used? 

I understand for php.ini

And, put his password in a file isnt dangerous?

**Comment by REJack** [comment]
SMTP is the Outgoing Mail Server Protocol. 

The Website (aauth) need a login for the smtp server, if you use an external smtp server or PHP's mail() is blocked like on mine servers. 

Excuse me you put your database password in a file too, its only dangerous if you have anonymous login for the webspace or a really easy password for ftp.


Von meinem iPhone gesendet

**Comment by Firefly16** [comment]
Ok, i got it. thx.

**Comment by Firefly16** [comment]
When i put my informations in:

```
'email_config'                => array(
                                        'protocol' => 'smtp',
                                        'smtp_host' => '>MY HOST<',
                                        'smtp_user' => '>MY MAIL<',
                                        'smtp_pass' => '>MY PW<',
                                        ),
```

it still give me: 

```
A PHP Error was encountered

Severity: Warning

Message: mail(): Failed to connect to mailserver at "localhost" port 25, verify your "SMTP" and "smtp_port" setting in php.ini or use ini_set()

Filename: libraries/Email.php

Line Number: 1845

Backtrace:

File: C:\xampp\htdocs\testing\application\libraries\Aauth.php
Line: 950
Function: send

File: C:\xampp\htdocs\testing\application\libraries\Aauth.php
Line: 755
Function: send_verification

File: C:\xampp\htdocs\testing\application\controllers\homepage.php
Line: 209
Function: create_user

File: C:\xampp\htdocs\testing\index.php
Line: 315
Function: require_once
```

**Comment by jmikerq** [comment]
Hi, I suggest adding proper documentation of the email config somewhere..... I was not able to find where to add the config parameters until I looked in the issues threads. Thanks!
