### ISSUE TITLE
Session remember me doesn't work.

### ISSUE THREAD

**Issue by terrylinooo** [emreakay/CodeIgniter-Aauth#154]
I test it by setting $config['sess_expiration'] = 10;

It doesn't work. CI will delete it and generate new session.

**Comment by REJack** [comment]
10 = 10 seconds
you should use 86400 for 1 Day or 3600 for 1 Hour.

**Comment by terrylinooo** [comment]
I know it. Even I set 3600 for 1 hour
$_SESSION['remember']  will be deleted after 1 hour, so how Session "remember me" work?

**Comment by REJack** [comment]
I've made a mistake :dizzy_face: when I added session for reCAPTCHA check (removed with v2.5.6).
The remember cookie is still needed, if `session_expiration` is `1 day` any login get remembered `1 day` not good.

I fixed this in [v2.5.7](https://github.com/emreakay/CodeIgniter-Aauth/releases/tag/v2.5.7).

**Comment by terrylinooo** [comment]
I think permanent remember is not a problem, most of popular website such of Github, Facebook.. they remember user login permanently.

To prevent someone steal cookie on user's computer and try illegal login

I use `define('COOKIE_REMEMBER_NAME', md5($_SERVER['HTTP_USER_AGENT'])); ` instead of 'user' cookie name, so load it by using
$this->CI->input->cookie(COOKIE_REMEMBER_NAME, TRUE);

It can improve security because the HTTP_USER_AGENT on different computer is almost different.

**Comment by REJack** [comment]
GitHub use a cookie too for remember user login `user_session` and session cookie `_gh_sess` as a non-expiring cookie (until browser is closed).

Thx for the hint with `HTTP_USER_AGENT`, i will try this and add this a further release.
