### ISSUE TITLE
Small bug in create_user() function.

### ISSUE THREAD

**Issue by waqas-ibrahim** [emreakay/CodeIgniter-Aauth#157]
```
// Update to correct salted password
			$data = null;
			if( !$this->config_vars['use_password_hash']){
				$data['pass'] = $this->hash_password($pass, $user_id);
			}
            
			$this->aauth_db->where('id', $user_id);
			$this->aauth_db->update($this->config_vars['users'], $data);
```

I have set "use_password_hash" to true in config file and as you can see the condition will fail and data array stays null. I am getting this error because of it.

> You must use the "set" method to update an entry.

**Comment by nimrod-cohen** [comment]
good catch @waqas-ibrahim 

and I would like to extend that during update_user the code ignores this setting at all:

if ($pass != FALSE) {
	if ( strlen($pass) < $this->config_vars['min'] OR strlen($pass) > $this->config_vars['max'] ){
		$this->error($this->CI->lang->line('aauth_error_password_invalid'));
		$valid = FALSE;
	}
	$data['pass'] = $this->hash_password($pass, $user_id);
}

If I set "use_password_hash" to false - it will still hash my password.

**Comment by waqas-ibrahim** [comment]
@nimrod-cohen It tries to update the password field with new generated password using user_id, but the condition fails as i have set 'use_password_hash' to true. So as i said earlier, data array is null hence the error.

**Comment by nimrod-cohen** [comment]
@waqas-ibrahim 
yes, correct, the entire update there is irrelevant when the password is not updated.
you're right on this issue.

**Comment by REJack** [comment]
guys i will look over it in 1-2hours

**Comment by REJack** [comment]
Guys i fixed the bug.

Please test the [develop](https://github.com/emreakay/CodeIgniter-Aauth/tree/develop)-branch.

**Comment by waqas-ibrahim** [comment]
Thanks @REJack :+1:
