### ISSUE TITLE
email_config error

### ISSUE THREAD

**Issue by tswagger** [emreakay/CodeIgniter-Aauth#158]
Getting a error when using an email config file.  When config file is named email.php it does NOT need to be initialized in CI3.
Severity: Notice
Message:  Undefined index: email_config
Filename: libraries/Aauth.php
Line Number: 912

Suggested fix:
change line 912 from
`if(is_array($this->config_vars['email_config'])){`
to
`if(isset($this->config_vars['email_config']) && is_array($this->config_vars['email_config'])){`

I am not sure if there are other ramifications to this suggested fix, but it eliminated the error I was getting.

**Comment by tswagger** [comment]
also on line 478

**Comment by REJack** [comment]
Hi Tim,

The error comes because the `email_config` isn't in the aauth's config file.

I'm doesn't know the trick with `email.php` :dizzy_face: , i fix it now and create a release for it.

**Comment by REJack** [comment]
Fix is released :smile:, now the `email.php` should work.

**Comment by REJack** [comment]
I'll close this issue, if the problem is still there reopen the issue :smiley:.
