### ISSUE TITLE
count_unread_pms includes deleted pms

### ISSUE THREAD

**Issue by paulcanning** [emreakay/CodeIgniter-Aauth#162]
`count_unread_pms` does not check the pm's deleted status.

This means if you delete a pm before reading it, it is still counted as unread.

https://github.com/emreakay/CodeIgniter-Aauth/blob/2.5-stable/application/libraries/Aauth.php#L2049

**Comment by REJack** [comment]
merged and released :+1:

**Comment by paulcanning** [comment]
Cheers

**Comment by stupidoes** [comment]
Related to this update, i think you should update sql file since two field that should be NULL ( pm_deleted_sender & pm_deleted_receiver ) have '0' as default.

**Comment by paulcanning** [comment]
I've submitted another PR to fix the SQL issue.
