### ISSUE TITLE
Remind password - Reset password

### ISSUE THREAD

**Issue by manukieli** [emreakay/CodeIgniter-Aauth#168]
The remind password function send to the user an email with the verification code.
When the user verify your identity the verify code is deleted from the database, but he don't receive the password. What can i need to do???
And the reset password function don't send a random password to the user.

**Comment by REJack** [comment]
With the latest Aauth version? (v2.5.10)
And which PHP version do you use?

**Comment by manukieli** [comment]
Yes, i'm using the latest version (2.5.10) and my php version is 5.5.38

**Comment by REJack** [comment]
Ok i check this later.

**Comment by REJack** [comment]
Sorry but i cant reproduce the error.

I think its a error by your mail server, check it with `$this->email->print_debugger(array('headers'));`

**Comment by manukieli** [comment]
Hi, yes i'm using the reset funtcion like this `reset_password($user_id, $ver_code)` and I've change it for
`reset_password($ver_code)` and work like a charme.
Thnak you for your help. ;)
