### ISSUE TITLE
Message: Only variables should be assigned by reference

### ISSUE THREAD

**Issue by timothymarois** [emreakay/CodeIgniter-Aauth#170]
> A PHP Error was encountered
> Severity: Notice
> Message: Only variables should be assigned by reference
> Filename: libraries/Aauth.php
> Line Number: 76

related to line
`$this->config_vars = & $this->CI->config->item('aauth');`

**Comment by REJack** [comment]
I doesn't get this notice and the line has no `&` by me. (that's cause the notice)

**Comment by timothymarois** [comment]
You are right. I just realized the version I have is out-of-date. `@version 2.0`
