### ISSUE TITLE
Performance Issue... Aauth very slow?

### ISSUE THREAD

**Issue by timothymarois** [emreakay/CodeIgniter-Aauth#171]
It appears there is a huge performance issue in Aauth. 

A blank CI 3.1.0 Install. (no db or aauth)
![screenshot 2016-08-10 15 56 12](https://cloud.githubusercontent.com/assets/2489333/17568763/1489c434-5f13-11e6-8597-8a6495effd91.png)

With Database: (this latency is bad because I'm going from local to datacenter)
`$autoload['libraries'] = array('database');`
![screenshot 2016-08-10 15 57 29](https://cloud.githubusercontent.com/assets/2489333/17568774/2cc12c0e-5f13-11e6-90d7-cd7db1a9149a.png)

and then when connecting Aauth to CI autoloader. (this is also not changing configurations, not using the aauth methods yet, just loading the library)
`$autoload['libraries'] = array('database','aauth');`
![screenshot 2016-08-10 15 59 30](https://cloud.githubusercontent.com/assets/2489333/17568824/703ae13c-5f13-11e6-9a2d-9b540a470b80.png)

For accurate results, let's run this many times to collect an average: 
Page rendered in 1.3715 seconds.
Page rendered in 1.6178 seconds.
Page rendered in 1.1887 seconds.
Page rendered in 1.0632 seconds.
Page rendered in 1.2852 seconds.
Page rendered in 1.6094 seconds.

Let's remove the database:
`$autoload['libraries'] = array('aauth');`

This is still terrible, half-a-second to load Authentication library that isn't even set to work with any controller methods yet. 

Page rendered in 0.5500 seconds.
Page rendered in 0.5779 seconds.
Page rendered in 0.8919 seconds.
Page rendered in 0.6023 seconds.

And to make this a controlled test, here is the stats of no database/aauth
`$autoload['libraries'] = array();`

Page rendered in 0.0098 seconds.
Page rendered in 0.0101 seconds.
Page rendered in 0.0091 seconds.
Page rendered in 0.0103 seconds.

**Comment by REJack** [comment]
Is this hosted by your self, if yes I'm noticed that the default config from mysql can be tweaked very well for more performance.

I'll check this tomorrow on my vServer, which PHP Version do you used?

**Comment by timothymarois** [comment]
Yes, right now this is a local env using `php 7.0.8`, the mysql database itself is hosted in a datacenter. But from the looks of it, removing the database from the tests shows that autoloading aauth itself is terribly slow, not sure what it is doing to increase the page loading times by that much, I know it requires a heavy amount of helpers/library dependancies. 

If I load all of those libraries within my own controller, aside from aauth, 
(loaded these in my welcome controller)
> $this->load->library('session');
> $this->load->library('email');
> $this->load->helper('url');
> $this->load->helper('string');
> $this->load->helper('email');
> $this->load->helper('language');
>$this->load->helper('recaptchalib');
>$this->load->helper('googleauthenticator_helper');
>$this->lang->load('aauth');

I'm only at Page rendered in 0.5425 seconds. (with only database autoloading), so to pinpoint it futher, it doesn't appear to be the dependancies (which looks to have no affect on loading times)

**Comment by REJack** [comment]
I see some changed for performance: (i'll add these tomorrow after the merges :smile:)
 - the helpers could be trigger to load only if needed
 - the email library could be loaded only in `reset_password` & `reset_password`
 - email & language helpers not used
 - `googleauthenticator_helper` is wrong `_helper` need to be removed
 - `recaptchalib` & `googleauthenticator` can be triggered trough a if

But i think its more that we connect to the database in `__construct`, that's get removed with v3.

**Comment by REJack** [comment]
O.K. sorry for the lack of info's and changes, I'm stuck hard in work.

I get with CI 3.1.0 & Aauth 2.5.10 on my little vServer PHP 5.5.9 + mySQL 5.5.47 (untweaked) much better times.

Without Aauth in Autoload:
> Page rendered in 0.0102 seconds. CodeIgniter Version 3.1.0 
> Page rendered in 0.0116 seconds. CodeIgniter Version 3.1.0 
> Page rendered in 0.0127 seconds. CodeIgniter Version 3.1.0 
> Page rendered in 0.0103 seconds. CodeIgniter Version 3.1.0 
> Page rendered in 0.0100 seconds. CodeIgniter Version 3.1.0 

With Aauth in Autoload:
> Page rendered in 0.0230 seconds. CodeIgniter Version 3.1.0 
> Page rendered in 0.0160 seconds. CodeIgniter Version 3.1.0 
> Page rendered in 0.0154 seconds. CodeIgniter Version 3.1.0 
> Page rendered in 0.0157 seconds. CodeIgniter Version 3.1.0 
> Page rendered in 0.0217 seconds. CodeIgniter Version 3.1.0

**Comment by timothymarois** [comment]
Interesting. Yeah I've been running it more, and appears to be running smoothly. Not sure why the benchmark I ran was showing ludicrous results. But it may have been from loading an older version of aauth. (which I think it's fixed). Thanks again for looking into it.
