### ISSUE TITLE
bug!

### ISSUE THREAD

**Issue by pars0097** [emreakay/CodeIgniter-Aauth#173]
when i rety to save a user with existing username i'll get error like this:

Account already exists on the system with that username. Please enter a different username, or if you forgot your password, please click the link below.
User does not exist
User does not exist
User does not exist
User does not exist
User does not exist
User does not exist
User does not exist

8 errors that just the first one is true!

pls fix it

**Comment by REJack** [comment]
Please give more informations (php & aauth version, local or online)

**Comment by pars0097** [comment]
i'm using current version of aauth php 5.6.20 on local

my controller:
`
        $this->load->model('UserModel');
        $this->load->library("Aauth");
        $this->load->helper('form');
        $this->load->library('form_validation');

               if (isset($_POST['register'])) {
            $validationConfig = $RegisterValidationConfig;

            $this->form_validation->set_rules($validationConfig);
            if ($this->form_validation->run() == FALSE) {
                $data['error'] = true;
                $data['body'] = $this->load->view('action/register',$data, true);
                $this->load->view('templates/temp_user',$data);
            }else {
                if ($this->UserModel->register() == true) {   
                    $this->load->view('action/register_success');
                }else{
                	$this->aauth->print_errors(); //show bad erros and exit
                    exit();;
                }
`
my model:
`
   public function register()
    {
        $name       = $this->input->post('name');
        $lastname   = $this->input->post('lastname');
        $major      = $this->input->post('major');
        $degree     = $this->input->post('degree');
        $email      = $this->input->post('email');
        $username   = $this->input->post('username');
        $phon       = $this->input->post('phon');
        $password   = $this->input->post('password');

        $q = $this->aauth->create_user($email,$password,$username);

        $this->aauth->set_user_var("name",$name,$q);
        $this->aauth->set_user_var("lastname",$lastname,$q);
        $this->aauth->set_user_var("major",$major,$q);
        $this->aauth->set_user_var("degree",$degree,$q);
        $this->aauth->set_user_var("phone",$phon,$q);
        $this->aauth->set_user_var("balance ",0,$q);
		
		return($q);
    }
`
output after enter existing username ($lastname):
`Account already exists on the system with that username. Please enter a different username, or if you forgot your password, please click the link below.
User does not exist
User does not exist
User does not exist
User does not exist
User does not exist
User does not exist`

**Comment by REJack** [comment]
That's not a bug my friend :smile:.
I had this problem in some projects too but, its not a bug you deliver to `set_user_var()` no user id because the creation fails.

You should make a `if` around your `set_user_var()` like this:
```php
   public function register()
    {
        $name       = $this->input->post('name');
        $lastname   = $this->input->post('lastname');
        $major      = $this->input->post('major');
        $degree     = $this->input->post('degree');
        $email      = $this->input->post('email');
        $username   = $this->input->post('username');
        $phon       = $this->input->post('phon');
        $password   = $this->input->post('password');

        $q = $this->aauth->create_user($email,$password,$username);
        
        if (is_numeric($q)){
                $this->aauth->set_user_var("name",$name,$q);
                $this->aauth->set_user_var("lastname",$lastname,$q);
                $this->aauth->set_user_var("major",$major,$q);
                $this->aauth->set_user_var("degree",$degree,$q);
                $this->aauth->set_user_var("phone",$phon,$q);
                $this->aauth->set_user_var("balance ",0,$q);
        }
        
        return($q);
    }

```

**Comment by pars0097** [comment]
thank you so much
i think it's better to create FAQ (or something like that) page in documentation for common problems and question like this one  :-)

**Comment by REJack** [comment]
good point :smile: i started writing a new documentation for v3 there i add a FAQ section.

**Comment by nimrod-cohen** [comment]
Doesn't the set_user_var change the current user if no user identification is passed?

**Comment by REJack** [comment]
if a user is loggedin you need not to pass the user id, but if you create a user over admin panel or register page then you should pass it like @pars0097 it does.
