### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by REJack** [emreakay/CodeIgniter-Aauth#174]
Hi everyone,

I'm have a the moment much work stress :tired_face:.

I'll create the next release at the weekend, with the 4 translations and little enhancements.

regards REJack

**Comment by pars0097** [comment]
good
and think its better to stop develop it for CI2
 nobody use ci2 now days (ci4 is coming)
and it increase performance

**Comment by REJack** [comment]
that comes with v3. 
the v2.5 is the latest version with CI2 support and it will have only bug fixes, minimal enhancements & translations and will get dropped with the release of version 3 for more informations see [here](151). 

CI4 is going to be a great release :smile:

**Comment by paulcanning** [comment]
Any updates @REJack ?

**Comment by REJack** [comment]
I'll push tomorrow the fixes and create a new release.

**Comment by pars0097** [comment]
loading...
please wait! :))

good news

**Comment by farhadhp** [comment]
Salam 

Bes nece oldu ?

**Comment by REJack** [comment]
sorry for the delay.

i published a new release [v2.5.11](https://github.com/emreakay/CodeIgniter-Aauth/releases/tag/v2.5.11)

**Comment by emreakay** [comment]
aleykumselem @farhadhp oldu oldu.
