### ISSUE TITLE
send activation email

### ISSUE THREAD

**Issue by steflight** [emreakay/CodeIgniter-Aauth#178]
since yesterday i try to config Aauth but , no mail sent

**Comment by REJack** [comment]
Hi whats your config settings for `email_config`?

**Comment by steflight** [comment]
'email_config'                => array(
                                         'user-agent' => 'Codeigniter',
                                        'protocol' => 'sendmail',
                                        'mail_path' => '/usr/sbin/sendmail',
                                        'mailtype' => 'html',          
                                        'smtp_user' => '',
                                        'smtp_pass' => '',
                                        ),

**Comment by REJack** [comment]
First overall do you use it from XAMPP or something like that? If yes sendmail isn't avaible there.
Second did you tried the `mail` protocol instead of `sendmail`?

**Comment by steflight** [comment]
i'm working on my online server
http://test.gethome.biz/t2/

**Comment by steflight** [comment]
when i try to send a simple mail with codeigniter as shown in documentation i succeed.

**Comment by steflight** [comment]
but there is problem when i try with Aauth

**Comment by REJack** [comment]
did you tried Aauth without config settings?

**Comment by steflight** [comment]
yes , with config_email = false

**Comment by REJack** [comment]
Place `$this->CI->email->print_debugger();` after `$this->CI->email->send();` in the `send_verification()` function of your Aauth.php

**Comment by steflight** [comment]
yes i put it ; 
1 - $this->aauth->create_user('agoumekoufanas@gmail.com','frodopass','god'); // my function
2 - 'email_config'                => array(
                                         'user-agent' => 'Codeigniter',
                                        'protocol' => 'sendmail',
                                        'mail_path' => '/usr/sbin/sendmail',
                                        'mailtype' => 'html',          
                                        'smtp_user' => '',
                                        'smtp_pass' => '',
                                        ),  // my config

**Comment by REJack** [comment]
did you get a output from `print_debugger()`?

**Comment by steflight** [comment]
yes  , click on this link : http://test.gethome.biz/t2/ 
i will check my email box

**Comment by REJack** [comment]
i dont see the output now it say its already registered 😄 
if you replace `create_user(*)` with `send_verification($this->aauth->get_user_id('agoumekoufanas@gmail.com'))` you can reproduce the debugger output.

**Comment by steflight** [comment]
please  try : http://test.gethome.biz/t2/

**Comment by REJack** [comment]
ok i see :D you need to change your mail from gmail block these if they are not correct.
> From: "Emre Akay" <admin@admin.com>

**Comment by steflight** [comment]
ok , i changed , i set my own email

**Comment by REJack** [comment]
thats spam like too and get blocked, set it like no_reply@test.gethome.biz

**Comment by REJack** [comment]
Oh and set your `base_url` in the config.php to set the correct link in the verification link.

**Comment by steflight** [comment]
this is my base_url ; $config['base_url'] = ''; , i set the email to no_reply@...

**Comment by REJack** [comment]
set it to `http://test.gethome.biz/t2/`

**Comment by REJack** [comment]
mail is ok check if you get your mail, it could be in your spam folder after the spam like sends 😄

**Comment by steflight** [comment]
![image](https://cloud.githubusercontent.com/assets/5181443/20668381/de615216-b56e-11e6-98d0-9cd28db8febf.png)
you are a genius , 
i want to contribute

**Comment by REJack** [comment]
perfect now you can remove the `print_debugger()` line.

At moment Aauth v3 is in development phase, if you have some feature suggestions post them in #151.

**Comment by steflight** [comment]
yes , great thank , are you on watsapp ?

**Comment by REJack** [comment]
yep i send you a mail 😸

**Comment by REJack** [comment]
You can close this issue, if its works right 😃

**Comment by REJack** [comment]
I'll close this issue, 
if you have some other problems feel free to open a new issue 😄
