### ISSUE TITLE
should be a function  :  is_member($userid, $group_par);

### ISSUE THREAD

**Issue by ibrahimuslu** [emreakay/CodeIgniter-Aauth#180]
There should be a function  :  is_member($userid, $group_par);

Admin could be manage users of groups and check if that user in that group

**Comment by REJack** [comment]
Hi @ibrahimuslu, 
it's is_member( $group_par, $user_id = FALSE ) available

**Comment by ibrahimuslu** [comment]
I cant see iy in wiki dovumentation. Sorry.

**Comment by REJack** [comment]
Oh thanks for the hint i'll add it later.
