### ISSUE TITLE
problem with login()

### ISSUE THREAD

**Issue by steflight** [emreakay/CodeIgniter-Aauth#182]
the hash code is code on 64 bit , while in database the password is 60 bit. 
i truncate with substr(), to manage it. i don't know if the issue is just caused by my database config or every one faced it

**Comment by REJack** [comment]
It seems that you used/imported the BCrypt SQL file instead of the normal (`Aauth_v2.sql`).

The only diffence between this 2 files is 
 - `Aauth_v2.sql` User password length is 64
 - `Aauth_v2_BCrypt.sql` User password length is 60

regards REJack

**Comment by steflight** [comment]
yes , i importe the both , ok we must precise it for the other person , 
thank @REJack 
i close the issue

**Comment by REJack** [comment]
I'll rewrite the "Installation and Configuration"-Wiki to catch this problem 😄 

In v3 the database gets generated trough the Aauth_Init Class
