### ISSUE TITLE
dynamically change Multilanguage support

### ISSUE THREAD

**Issue by ibrahimuslu** [emreakay/CodeIgniter-Aauth#183]
I want to change my system language based on a selection of user. And I have built one but in aauth library the language files are loaded as default config language.
I have changed the line as:

`
		$this->CI->lang->load('aauth',$this->CI->session->userdata('language'));
`
I don't know if it is a global solution but it is OK for me. 

I think changing language dynamically should be a feature.

**Comment by REJack** [comment]
@ibrahimuslu It's not so good to add this into CodeIgniter-Aauth, it would only change Aauth's language that is not effective. 
This should be added to a controller to change all languages (not only Aauth's) on a CI project that would change Aauth's langauge too.

Sorry, but i reject/close this issue.
