### ISSUE TITLE
verification link

### ISSUE THREAD

**Issue by Firefly16** [emreakay/CodeIgniter-Aauth#185]
Hi, it's been a while ! 

I finally started to work on email. When I receive the verification link and clic on it I have: 

"404 Page Not Found

The page you requested was not found."

I'm working on an url like this http://46.38.xxx.xxx/. I don't know if it matter. Also the link send me to my index with this in addition "account/verification/28/OhQ3intk5CLBog1E"

EDIT:
Note that smtp_host etc settings are done on CI library and not on aauth config.
And in database all rows are NULL exept "email, pass, name, banned (on 1), verification code and login attempt (0)."

**Comment by REJack** [comment]
Did you set the base_url in CI's config.php?

**Comment by Firefly16** [comment]
I have a custom base url in CI but I didn't change any link on verification code. Do we have to change something? (i though it was taking the base url by default)

**Comment by REJack** [comment]
Thats strange i had never problems with this 😢 Which CI version you use?

**Comment by Firefly16** [comment]
3.0.6 I think

**Comment by Firefly16** [comment]
I just create a user `$this->aauth->create_user($email, $password, $data['nickname']);` and put verification on true `'verification'                   => true`

Perhaps I miss one step?

**Comment by REJack** [comment]
Nope, that is all.

Whats does your `base_url & index_page` contains?

**Comment by Firefly16** [comment]
$config['base_url'] = 'http://46.38.xxx.xxx/testing/company/'; 
$config['index_page'] = 'index.php';

**Comment by REJack** [comment]
And you how looks the link in the mail?

Like this? http://46.38.xxx.xxx/testing/company/account/verification/28/OhQ3intk5CLBog1E

**Comment by Firefly16** [comment]
http://46.38.xxx.xxx/testing/company/index.php/account/verification/28/OhQ3intk5CLBog1E

**Comment by REJack** [comment]
Mmmh that should work, do you created a account controller with a verification function for this?

**Comment by Firefly16** [comment]
I don't have a verification function no

**Comment by REJack** [comment]
you need to create a verification function inside your account controller.

**Comment by REJack** [comment]
Aauth v2 doesn't deliver any UI thats why there no controller for this, but in v3 we add a UI for Login, User Managment, etc 😄

**Comment by Firefly16** [comment]
Ok ^^'

So I have to make a `verify_user($user_id, $ver_code)` where people can put their code to verify their account. But it won't fix the link problem I guess? So the only option left is to verify with the code?

**Comment by REJack** [comment]
Do you have a account Controller? If yes, a verification function would fix your 404 error.

**Comment by Firefly16** [comment]
I though you meant that a account controller was a controller I created for all personal account functions.

What is a account controller?

**Comment by REJack** [comment]
yes that i mean :D there are all public functions with its UI like register, login, forgot pw, edit pw, show profile and other stuff, there should be a verification too.

**Comment by Firefly16** [comment]
```
public function verification(){
        
        if($this->input->post('submit_verification')){
            $user_id = $this->input->post('id');
            $ver_code = $this->input->post('verification');
            $this->aauth->verify_user($user_id, $ver_code);
        }else{
            $this->load->view('verification_view');
        }
        
        
    }
```

I created this fast on my user controller (doesnt have the 'account' name but 'user'). Still not working :(

**Comment by Firefly16** [comment]
If fact you asked me to create the  http://46.38.xxx.xxx/testing/company/index.php/account/verification link where id is for example 29 and code is OBN6nWsupfAYTDrv to autocomplete a form with those 2 informations and then the user can submit thoses values right?

**Comment by REJack** [comment]
oh if its not named account you need to change the verification_link

**Comment by REJack** [comment]
the default is  'verification_link' => '/account/verification/'

**Comment by Firefly16** [comment]
I'm not banned anymore so I guess it's ok :D

Sorry it was a dumb mistake from me, didn't make any CI code from a while ^^

**Comment by REJack** [comment]
no problem :D

**Comment by REJack** [comment]
I forgot to ask too 😭 😄

**Comment by Firefly16** [comment]
It was good to see you again :D I lock ^^
