### ISSUE TITLE
reset_password information

### ISSUE THREAD

**Issue by macka601** [emreakay/CodeIgniter-Aauth#186]
Hi - Just wondering if you could fill me in a little on how reset_password is supposed to work.. 
My intention is to use it for an admin to reset the password, so i would have thought it would have reset_password($id, $code).
is there another way it should be used? it doesn't seem tied to any particular user, logged in or not.. 

Thanks

**Comment by REJack** [comment]
Oh you read the Wiki and its out of date :/.

It's now only `reset_password($ver_code)` but you need the code before that goes out over a email with `remind_password($email)`. 

`reset_password()` is only there for forgotten passwords not for change pw thats handled over `update_user($user_id, $email = FALSE, $pass = FALSE, $username = FALSE)`

**Comment by macka601** [comment]
I had read the wiki - where it was `reset_password($ver_code)` but i couldn't make it relate to a user_id.. 

Have switched to your suggestion about the remind password.. thanks for your help!

**Comment by REJack** [comment]
The relation to a user_id is over the specific code thats generated on `remind_password()`.

Changed since #124.

regards REJack
