### ISSUE TITLE
is_group_allowed will always be the true value.

### ISSUE THREAD

**Issue by tedileader** [emreakay/CodeIgniter-Aauth#22]
i like Aauth. i love Aauth...
But I request to you.
This will be true for this function is allowed and is_group_allowed.
It is very dangerous code when admin permissions and group permissions check.
I request to the code Delete or Change. 

$group_pars = $this->list_groups();
            foreach ($group_pars as $g ){
                if($this->is_group_allowed($perm_id, $g->id)){
                    return true;
                }
            }

i try admin or admingroup checking code:

if(!$this->aauth->is_group_allowed(1)):
				$this->session->flashdata('message','회원님은 관리자가 아닙니다. 지속적으로 접속 시도할시에 자동으로 정지처리 됩니다.');
				redirect('/');
			endif;

But this code always return true...
I request to the code Delete or Change.

**Comment by emreakay** [comment]
closed .
