### ISSUE TITLE
New Place for us!

### ISSUE THREAD

**Issue by emreakay** [emreakay/CodeIgniter-Aauth#242]
Hi Dear Aauth Users and My Friends,

As I shut my Software Engineering Company (Magefly) due to economic crisis;
I have taken the ownership of the Aauth again.

In 2019, we will be preparing Aauth to CI4.

CI4 comes with very cool features, and AAuth as well.

Have a nice weekend.

**Comment by rmcdahal** [comment]
Please make first round upgrade,then will submit pr and patch..

**Comment by engrsandeep** [comment]
Hi @emreakay is ci4 version available?

**Comment by rmcdahal** [comment]
Checkout dev branch 
https://github.com/emreakay/CodeIgniter-Aauth/tree/v3-dev
