### ISSUE TITLE
Portuguese Translation

### ISSUE THREAD

**Issue by balduinofernando** [emreakay/CodeIgniter-Aauth#243]
Hey guys...
I have translated the library messages into Portuguese Language.
Could you please merge in the next release?

<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/* E-mail Messages */

// Account verification
$lang['aauth_email_verification_subject'] = 'Verificação de Conta';
$lang['aauth_email_verification_code'] = 'O seu código de verificação é: ';
$lang['aauth_email_verification_text'] = "Também podes clicar em (Copiar e Colar) \n\n";

// Password reset
$lang['aauth_email_reset_subject'] = 'Repôr a senha';
$lang['aauth_email_reset_text'] = "Para repôr a senha clique em (Copiar e Colar na barra de endereço do seu navegador) o link abaixo:\n\n";

// Password reset success
$lang['aauth_email_reset_success_subject'] = 'Senha reposta com sucesso';
$lang['aauth_email_reset_success_new_password'] = 'A sua senha foi reposta com sucesso. A sua nova senha é: ';

/* Error Messages */

// Account creation errors
$lang['aauth_error_email_exists'] = 'Este endereço de e-mail já existe no sistema. Se esqueceste a senha, podes clicar no link abaixo.';
$lang['aauth_error_username_exists'] = "Já existe uma conta no sistema com este nome de usuário. Por favor seleccione um nome de usuário diferente, ou se esqueceu a senha, por favor clique no link abaixo.";
$lang['aauth_error_email_invalid'] = 'Endereço de e-mail inválido.';
$lang['aauth_error_password_invalid'] = 'Senha Inválida';
$lang['aauth_error_username_invalid'] = 'Nome de Usuário Inválido';
$lang['aauth_error_username_required'] = 'Nome de Usuário Obrigatório';
$lang['aauth_error_totp_code_required'] = 'Código de Autenticação Obrigatório';
$lang['aauth_error_totp_code_invalid'] = 'Código de Autenticação Inválido';

// Account update errors
$lang['aauth_error_update_email_exists'] = 'Este endereço de e-mail já existe no sistema. Por favor digite um endereço de e-mail diferente.';
$lang['aauth_error_update_username_exists'] = "Já existe uma conta no sistema com este nome de usuário. Por favor digite um nome de usuário diferente.";

// Access errors
$lang['aauth_error_no_access'] = 'Desculpe, não tens acesso a este recurso.';
$lang['aauth_error_login_failed_email'] = 'O E-mail e a Senha não estão corretos.';
$lang['aauth_error_login_failed_name'] = 'Nome de Usuário e a senha não estão corretos.';
$lang['aauth_error_login_failed_all'] = 'Email, Nome de Usuário ou a Senha não estão corretos.';
$lang['aauth_error_login_attempts_exceeded'] = 'Você excedeu as tentativas de login, a sua conta foi desativada.';
$lang['aauth_error_recaptcha_not_correct'] = 'Desculpe, o texto do reCAPTCHA foi digitado incorretamente.';

// Misc. errors
$lang['aauth_error_no_user'] = 'Este Usuário não existe';
$lang['aauth_error_vercode_invalid'] = 'Código de Verificação Inválido';
$lang['aauth_error_account_not_verified'] = 'A sua conta não foi verificada. Por favor abra seu e-mail e verifique a sua conta.';
$lang['aauth_error_no_group'] = 'O grupo nao existe';
$lang['aauth_error_no_subgroup'] = 'O Subgrupo não existe';
$lang['aauth_error_self_pm'] = 'Não é possível mandar mensagem para você mesmo.';
$lang['aauth_error_no_pm'] = 'Mensagem privada não encontrada';

/* Info messages */
$lang['aauth_info_already_member'] = 'O Usuário já é membro do grupo';
$lang['aauth_info_already_subgroup'] = 'O Subgrupo já é membro do grupo';
$lang['aauth_info_group_exists'] = 'Nome de grupo já existe';
$lang['aauth_info_perm_exists'] = 'Nome de permissão já existe';

**Comment by emreakay** [comment]
Hi, 
We will merge it, thanks for your this valuable contribution.

**Comment by balduinofernando** [comment]
No problem.
**It is an awesome library**, the more we contribute the more full-featured it becomes.
