### ISSUE TITLE
set_user_var() BUG

### ISSUE THREAD

**Issue by code2prog** [emreakay/CodeIgniter-Aauth#25]
```php
$this->aauth->unset_user_var( "possible_accounts" );
$this->aauth->set_user_var( "possible_accounts", 0 );

$possible = (int) $this->aauth->get_user_var( "possible_accounts" ) + 3;
$this->aauth->set_user_var( "possible_accounts", $possible );
```
the code above should end with only one record in database with value 3, but for some reason in database are two separate records with the key"possible_accounts" assigned to the same user with value 0 and 3. For some reason update is not working properly. I tried to find error there but I couldn't find it.

**Comment by emreakay** [comment]
ok @REJack :)

**Comment by REJack** [comment]
Please close #19, #20, #21, #23, #29, #36, #39 too.
