### ISSUE TITLE
How attemp remove when successfully login or manual call function

### ISSUE THREAD

**Issue by byruddy** [emreakay/CodeIgniter-Aauth#252]
Please help me, i config to be true for ` 'remove_successful_attempts'     => true,` but still can't 

and i using function `$this->aauth->_reset_login_attempts(1);` same,

my question what is parameter means for 1 because in table id is increment not ref by id user :(

please help my life

**Comment by REJack** [comment]
Its only `$this->aauth->reset_login_attempts();`, reset_login_attempts removed login attempts based on ip address so you will not need any user id.

**Comment by byruddy** [comment]
> Its only `$this->aauth->reset_login_attempts();`, reset_login_attempts removed login attempts based on ip address so you will not need any user id.

thank you so much, btw all function already to be use ? alright ?
