### ISSUE TITLE
Can i create some more columns in Aauth users table ?

### ISSUE THREAD

**Issue by ikramkhizar** [emreakay/CodeIgniter-Aauth#253]
i want to create three more columns in aauth users that will be first_name, last_name, mobile_no
is that worked ? and what are the side effects of creating manual columns

**Comment by emreakay** [comment]
u can also use user_variables for that kind of issues.
https://github.com/emreakay/CodeIgniter-Aauth/wiki/7)-User-Variables

**Comment by ikramkhizar** [comment]
but that's to complex if i want to get three user variables, it's easy to get aauth users table if it is there

**Comment by mhcifci** [comment]
> but that's to complex if i want to get three user variables, it's easy to get aauth users table if it is there
You can add columns to the table.

And I'd like to say a simpler method. You can bring user data with a simple function.

- First create a helper file.
```
    // @info: Getting userdata with object
    function userData(){
        $t = &get_instance();
        return $t->aauth->get_user();
    }
```
- Init the helper file in autoload. (application/config/autoload.php)
- Init the Aauth library in autoload. (application/config/autoload.php)

Wherever you use it, just write it like this.

`<?php userData()->name ?>`

Best Regards
