### ISSUE TITLE
Upgrade it to Codeigniter 4

### ISSUE THREAD

**Issue by matheuscastroweb** [emreakay/CodeIgniter-Aauth#257]
With this sad [post ](https://forum.codeigniter.com/thread-75235.html)on the forum, I believe Codeigniter 4 is closer than ever.

What do you think of an update branch for v4?

**Comment by REJack** [comment]
Aauth is already ready for CI4, you can take a look at the [v3-dev branch](https://github.com/emreakay/CodeIgniter-Aauth/tree/v3-dev). I've waited only for some final releases after the rc stucked at rc.3.

**Comment by matheuscastroweb** [comment]
Really. I saw v3_branch and thought it was CI3, I didn't go to the branch to check it out. Very good. Closing this topic.
