### ISSUE TITLE
Create group return 0 when success

### ISSUE THREAD

**Issue by bagaskarala** [emreakay/CodeIgniter-Aauth#258]
Why `$this->aauth->create_group("editor", "group for editor");`  return 0 when it is success, and return nothing when failed?

When i this code i if block, it will never return true value

**Comment by REJack** [comment]
It returns the group id if it successfully inserted and `false` if not.

**Comment by bagaskarala** [comment]
> It returns the group id if it successfully inserted and `false` if not.

I reproduce the error below:

Database before new group created
![before](https://user-images.githubusercontent.com/14112952/75008849-b3befb00-54ab-11ea-8934-ff44bef8a36d.png)

My code to create group
![code](https://user-images.githubusercontent.com/14112952/75008875-cafde880-54ab-11ea-86e0-44da3ba530a4.png)

When i call the function
![func invoke](https://user-images.githubusercontent.com/14112952/75008901-d81ad780-54ab-11ea-8cc9-38142ac961c9.png)

It success created, but i wonder why returned value is 0
![after](https://user-images.githubusercontent.com/14112952/75008917-e36e0300-54ab-11ea-8f10-d3d67602e4dc.png)

I'm using PHP 7.3.10 and codeigniter 3.1.11

**Comment by REJack** [comment]
I see what you mean and fixed it already on master branch, this was caused by the pre-caching feature 🤦‍♂.

**Comment by bagaskarala** [comment]
> I see what you mean and fixed it already on master branch, this was caused by the pre-caching feature 🤦‍♂.

Okay thanks it now works properly

**Comment by emreakay** [comment]
:+1: Thank everyone
