### ISSUE TITLE
CodeIgniter-Aauth v3  Getting Login Error

### ISSUE THREAD

**Issue by mehmetsarr** [emreakay/CodeIgniter-Aauth#262]
I'm getting http://www.domain.com/ci/account/login page not found error. How can I redirect Routes.php?

**Comment by mehmetsarr** [comment]
Merhaba

**Comment by emreakay** [comment]
Merhabalar.

**Comment by mehmetsarr** [comment]
Hocam ci 4 için sql dosyası yok mu acaba
