### ISSUE TITLE
Sql file for CodeIgniter 4-Aauth v3

### ISSUE THREAD

**Issue by mehmetsarr** [emreakay/CodeIgniter-Aauth#263]
Hi No sql file for CodeIgniter 4-Aauth v3? I am installing the ci 3 sql file, the user says wrong information.

**Comment by REJack** [comment]
CodeIgniter-Aauth v3 has no SQL File, v3 comes with migrations.

**Comment by emreakay** [comment]
hi, 
as @REJack said, 
you must use migration insted of importing sql.

**Comment by mehmetsarr** [comment]
> CodeIgniter-Aauth v3 has no SQL File, v3 comes with migrations.

How can I do that? Can you give me information about this?

**Comment by REJack** [comment]
@mehmetsarr look at the CodeIgniter 4 [docs](https://codeigniter4.github.io/CodeIgniter4/dbmgmt/migration.html#id6).
