### ISSUE TITLE
Is it compatible with CodeIgniter 3?

### ISSUE THREAD

**Issue by OlexandrPopov** [emreakay/CodeIgniter-Aauth#36]

**Comment by REJack** [comment]
i dont know if it works with the 3.0 release but with the 3.0-develop it has worked.
in the last update of Aauth i added an CI3 fix and reCaptcha ^^

**Comment by kamekun** [comment]
Where i can find trhis 3.0-develop ????

**Comment by REJack** [comment]
https://github.com/bcit-ci/CodeIgniter/ its the develop branch but it should work with the released version of CI3

**Comment by REJack** [comment]
the develop isn't stable

**Comment by kamekun** [comment]
sorry I thought you meant to version 3.0 of the library aauth not CI. I think The current library of Aauth need  to fix some bugs.

**Comment by REJack** [comment]
which bugs? i use it on my projects i found no :smile:

**Comment by REJack** [comment]
in my opinion its too complex for a single library without models, it would better with models
