### ISSUE TITLE
Login and creating new account problem

### ISSUE THREAD

**Issue by rocodou** [emreakay/CodeIgniter-Aauth#41]
Hello, Database "pass" field is 50 length. But Sha256 hash length is 64 there have is problem. Please fixit. :)

**Comment by REJack** [comment]
It's already fixed in PR #40 it only needs to merge

**Comment by emreakay** [comment]
Hi guys im going to merge this night all of them

**Comment by keroloswilliam** [comment]
i have problem in login function 
it always return false even when i send the email and password hardcoded

**Comment by keroloswilliam** [comment]
i changed the sh256 to md5 so the hash code was changed from 64 to 32 and the login now working fine

**Comment by emreakay** [comment]
@keroloswilliam i merged it. im sorry for latency :)
