### ISSUE TITLE
check_email(), still a valid function?

### ISSUE THREAD

**Issue by ManeBit** [emreakay/CodeIgniter-Aauth#44]
I was trying to use this function but it appears that it is not in the Aauth library?

https://github.com/emreakay/CodeIgniter-Aauth/wiki/4%29-User-Operations#check_emailemail

**Comment by REJack** [comment]
its has renamed now its user_exsist_by_email($email) it returns TRUE if email exists in DB

**Comment by jacobtomlinson** [comment]
Perhaps the docs should be included in the repo as markdown files. That way they can easily be kept up to date with the project.

**Comment by REJack** [comment]
i work at the moment on a documentation for Aauth on readthedocs.org
