### ISSUE TITLE
Updating user doesn't work, library raises warnings

### ISSUE THREAD

**Issue by neilsf** [emreakay/CodeIgniter-Aauth#50]
Hi, thanks for this great library!

I ran into some issue now, it's strange, this was working before. When I call:

`$this->aauth->update_user("6", false, false, "New name");`

The user is never updated and I receive the following warnings:

Message: Undefined variable: valid
Filename: libraries/Aauth.php
Line Number: 714

Message: Invalid argument supplied for foreach()
Filename: libraries/Aauth.php
Line Number: 1774

version 2.0

**Comment by neilsf** [comment]
Line 714 should be:

`if (isset($valid) && !$valid) {`

... and it works

**Comment by REJack** [comment]
nope 
there is no `$valid = TRUE;` in line 679 thats why its crashs and its already a PR #45 there to fix it

**Comment by neilsf** [comment]
OK, thanks.
