### ISSUE TITLE
is_allowed() bug

### ISSUE THREAD

**Issue by neilsf** [emreakay/CodeIgniter-Aauth#51]
Say you wanna find out if a user (other than the currently logged in user) has a permission. You call `is_allowed($perm_par, $user_id)`.

Then `is_allowed()` does the following:

- Checks for matching rows in `perm_to_user` table. If found, returns true.
- If not found, it will call `is_group_allowed($perm_id)` to see if the user's groups have the perm, without the second parameter.

But `is_group_allowed($perm_id, false)` checks for *the currently logged in user's permission*, this is not the expected behaviour.

I suggest to perform a different check arround line 1366:

    if( $query->num_rows() > 0){
        return TRUE;
           } else {
			
			if( $user_id===FALSE){
				return $this->is_group_allowed($perm_id);
			} else {
				$g_allowed=FALSE;
				foreach( $this->get_user_groups($user_id) as $key=>$group ){
					if ( $this->is_group_allowed($perm_id, $group->id) ){
						$g_allowed=TRUE;
					}
				}
				
				return $g_allowed;
			}
		}

**Comment by ManeBit** [comment]
@REJack Thoughts on this?

http://codeigniter-aauth-test.readthedocs.org/en/latest/functions/permissions.html#is_group_allowed

**Comment by REJack** [comment]
it looks correct, i would add a PR if nobody else do it :smile:

**Comment by ManeBit** [comment]
go for it ;)

**Comment by REJack** [comment]
only what i need is to get #52 merged, then i can refork it and i can add the PR :P

**Comment by emreakay** [comment]
I am going to merge it tonight :)

**Comment by ibrahimuslu** [comment]
did you merge this?

**Comment by emreakay** [comment]
Yes I did İbrahim

**Comment by REJack** [comment]
@emreakay, when you merge it? 

i want to write a new PR for the pm idea https://github.com/emreakay/CodeIgniter-Aauth/issues/49#issuecomment-125784258 :smile:

**Comment by emreakay** [comment]
I'm going to merge it in 2 days

**Comment by emreakay** [comment]
@REJack, merged
