### ISSUE TITLE
Logo for Aauth

### ISSUE THREAD

**Issue by ManeBit** [emreakay/CodeIgniter-Aauth#54]
### I've been working on a simple logo for Aauth.
==
![aauth](https://cloud.githubusercontent.com/assets/2959172/8920984/2b337388-3485-11e5-89dc-38a13f9dd8a8.png)
==
And the banner form.
![banner](https://cloud.githubusercontent.com/assets/2959172/8921180/40936894-3487-11e5-847b-0d671405caa6.png)

#### Any suggestions?

**Comment by lazho** [comment]
![aauth](https://cloud.githubusercontent.com/assets/2417212/8925689/add409ea-34be-11e5-8e50-845da8f5b1b0.png)

This one is available in svg, and the png export is 5000x5000. It kind of fits better in the "flat" design of win8 or material design. If that matters anyways.

**Comment by ManeBit** [comment]
Looks like my friend has outdone me... @lazho Thanks Lance. I'll make a banner version for yours too

**Comment by ManeBit** [comment]
![banner2](https://cloud.githubusercontent.com/assets/2959172/8925836/de3fd766-34bf-11e5-84c3-16c9c0d13797.png)

**Comment by REJack** [comment]
both looks nice, i like more the flat one :smile:

**Comment by jacobtomlinson** [comment]
Yep I like the flat one too.

**Comment by tswagger** [comment]
I like the flat version as well.  Understated and eloquent.

**Comment by emreakay** [comment]
Both of them very good works but I like flat one as well :)

**Comment by neilsf** [comment]
+1 vote for the flat version.
The other one is also a nice job as well ;-)

**Comment by emreakay** [comment]
Thank you for everyone we are going to use this logo from now on

**Comment by ManeBit** [comment]
Perfect!
