### ISSUE TITLE
Login method always returns false

### ISSUE THREAD

**Issue by edithtats** [emreakay/CodeIgniter-Aauth#56]
Hi!

I initiate myself to codeigniter and i downloaded CodeIgniter-Aauth library for authentication of users in my project. I followed all the steps needed to install the library but when i want to use the "login" method in a controller, this method always returns false. For example, when i want to check if the entered values in the login form are present in database...

Please help me

**Comment by REJack** [comment]
which version of CodeIgniter do you use?
which version of CodeIgniter-Aauth do you use?

**Comment by edithtats** [comment]
Version of CodeIgniter : 3
Version of Codeigniter-Auth : 2

**Comment by REJack** [comment]
CodeIgniter-Aauth: 2.2.0 or 2.3.0?

**Comment by edithtats** [comment]
CodeIgniter-Aauth : 2.0

**Comment by REJack** [comment]
this version doesnt work with CI3 only 2.2.0 and 2.3.0 work with CI3 (but if you use 2.3.0 you should use this [sql file](https://raw.githubusercontent.com/REJack/CodeIgniter-Aauth/master/sql/Aauth_v2.sql))

**Comment by edithtats** [comment]
Thank you
I will try with both versions

**Comment by edithtats** [comment]
Please can i have the link for CodeIgniter-Aauth 2.3.0?

**Comment by edithtats** [comment]
I try the same operation (log a user in the system) and i have the same problem. The login method returns false. But when i check the "aauth_users" table in my base, the fields "last_login_attempt" and "login_attempts" are modified.
CodeIgniter-Aauth : 2.3.0

**Comment by REJack** [comment]
is any user in the "aauth_users" table? With the Original SQL file from 2.3.0 it generates errors.

**Comment by edithtats** [comment]
yes i created one user in "aauth_users" table and when i am logging in the system with Admin i have the same problem

**Comment by REJack** [comment]
do you use the old database from 2.0 or used the file from 2.3.0?

**Comment by edithtats** [comment]
i use the database the old database from 2.0

**Comment by REJack** [comment]
then drop the hole database and use this [sql file](https://raw.githubusercontent.com/REJack/CodeIgniter-Aauth/master/sql/Aauth_v2.sql)

**Comment by edithtats** [comment]
Ok i will try it

**Comment by edithtats** [comment]
I drop the database and use that sql file but i still have the same problem

**Comment by edithtats** [comment]
maybe because i store the sessions in database? in a table named "ci-sessions"

**Comment by REJack** [comment]
do you get aauth errors or ci errors?

**Comment by edithtats** [comment]
I solved the problem

**Comment by edithtats** [comment]
it was because i created user with database manager

**Comment by edithtats** [comment]
now i create a user with "create_user" method and the login method now returns true

**Comment by REJack** [comment]
the password was net correct stored :+1:

**Comment by REJack** [comment]
then you can close this issue if its works :smile:

**Comment by edithtats** [comment]
thank you once again
