### ISSUE TITLE
SQL error: Column count doesn't match value count at row 1

### ISSUE THREAD

**Issue by hbinded** [emreakay/CodeIgniter-Aauth#57]
On importing the Aauth_v2.sql I got the error that the column count doesn't match the value count. This is because at line 129, it ready
<pre>
INSERT INTO `aauth_users` VALUES ('1', 'admin@example.com', 'dd5073c93fb477a167fd69072e95455834acd93df8fed41a2c468c45b394bfe3', 'Admin', '0', null, null, null, null, null, null, null, null, '0');
</pre>
so the "ip_address"  column isn't accounted for.

I'm new to github so I don't really know how to contribute patches. This worked for me:
<pre>
--- Aauth_v2.sql	2015-08-13 14:51:14.682800397 +0200
+++ Aauth_v2.1.sql	2015-08-13 14:52:08.034799843 +0200
@@ -126,7 +126,7 @@
 -- ----------------------------
 -- Records of aauth_users
 -- ----------------------------
-INSERT INTO `aauth_users` VALUES ('1', 'admin@example.com', 'dd5073c93fb477a167fd69072e95455834acd93df8fed41a2c468c45b394bfe3', 'Admin', '0', null, null, null, null, null, null, null, null, '0');
+INSERT INTO `aauth_users` VALUES ('1', 'admin@example.com', 'dd5073c93fb477a167fd69072e95455834acd93df8fed41a2c468c45b394bfe3', 'Admin', '0', null, null, null, null, null, null, null, null, '127.0.0.1', '0');
 
 -- ----------------------------
 -- Table structure for `aauth_user_to_group`

</pre>

**Comment by REJack** [comment]
its already in my PR, i wrote this failure in my last feature :smile: a fixed sql file is [here](https://raw.githubusercontent.com/REJack/CodeIgniter-Aauth/master/sql/Aauth_v2.sql)

**Comment by hbinded** [comment]
Oh okay, didn't check your pr. Thanks for the heads up. closing this now.
