### ISSUE TITLE
Fatal error: has_userdata is not defined.

### ISSUE THREAD

**Issue by cekdahl** [emreakay/CodeIgniter-Aauth#58]
I'm getting this error message:

> PHP Fatal error:  Call to undefined method CI_Session::has_userdata() in /path/to/codeigniter/application/libraries/Aauth.php on line 400

I have checked the session library in Codeigniter 2.2.3 and there is indeed no such function. There is a [forum thread](http://forum.codeigniter.com/archive/index.php?thread-61520.html) which indicates that it was deprecated a while ago.

**Comment by REJack** [comment]
i've added a fix for it in my PR i hope emre merge it in the next days.

thx for reporting the error :smile:

**Comment by cekdahl** [comment]
Thank you for working on this library!

**Comment by emreakay** [comment]
merged :)
