### ISSUE TITLE
A problem with get_(errors|infos)_array

### ISSUE THREAD

**Issue by cekdahl** [emreakay/CodeIgniter-Aauth#59]
In the constructor of the library file there is this line:

		$this->errors = $this->CI->session->flashdata('errors');
		$this->infos = $this->CI->session->flashdata('infos');

The problem with this is that that if errors and infos do not exist, the flashdata returns `FALSE`. So later in the `get_(errors|infos)_array` functions that look like this

	public function get_infos_array()
	{
		if (!count($this->infos)==0)
		{
			return $this->infos;
		}
		else
		{
			return array();
		}
	}

it doesn't end up right. When the argument of `count` is not an array or an object implemented with the `Countable` interface, `count` returns 1. So actually the above function returns `FALSE` when no messages have been specified, instead of an empty array. This became a problem for me, so I've temporarily fixed it like this:

		$this->errors = $this->CI->session->flashdata('errors') ?: array();
		$this->infos = $this->CI->session->flashdata('infos') ?: array();

And I also believe that you could write the above function like this:

    public function get_infos_array()
    {
        return $this->infos;
    }

**Comment by REJack** [comment]
not really, if $this->errors is empty it returns not ``FALSE`` it returns ``NULL`` so  ``print_r(count($this->infos));`` will return 0 and not 1

i've tested it with my Linux VPS and my Windows XAMPP same result.

**Comment by cekdahl** [comment]
I'm sorry, but you are wrong. What I wrote is correct.

**Comment by REJack** [comment]
we are both right 
you tested it on CI 2.2
i tested it on CI 3

**Comment by cekdahl** [comment]
I guess you are behind the updates that cause the library to not work on CodeIgniter 2.x. I am of the opinion that we are **not** both right, and that @emreakay should not have accepted your pull request until it was made compatible 2.x. It is clearly stated in the description of this library is for Codeigniter 2.x.

**Comment by cekdahl** [comment]
And, just to make sure I'm being understood, this is not legalism. I'm not just saying these things to be right. The problem is that when people such as I search for an authorization library for Codeigniter 2.x we're directed here, and start writing code in Codeigniter 2.x with this library thinking that it will work. But then when we run the code it turns out that it doesn't, and so we have to spend time to figure it out. I'm not saying the maintainers of this library cannot possibly drop support for 2.x - I'm just saying that it's evil to write that it's for 2.x when it's not compatible with 2.x.

**Comment by REJack** [comment]
@cekdahl i understood your opinion, can you close this issue? emre merged your PR and changed the Info Text to `2.x and 3.x`

**Comment by cekdahl** [comment]
@REJack I forgot about that. It's now done.

**Comment by REJack** [comment]
thx :smiley:
