### ISSUE TITLE
Undefined method CI_Session::tempdata()

### ISSUE THREAD

**Issue by cekdahl** [emreakay/CodeIgniter-Aauth#61]
I get this error:

> PHP Fatal error:  Call to undefined method CI_Session::tempdata() in /path/to/codeigniter/application/libraries/Aauth.php on line 225

because `tempdata` only exists in CodeIgniter 3, not 2.x.

This issue is related to #58 which is about another function that is only available in Codeigniter 3.

**Comment by emreakay** [comment]
merged @REJack and @cekdahl
