### ISSUE TITLE
how to create custom fields

### ISSUE THREAD

**Issue by vishals321** [emreakay/CodeIgniter-Aauth#64]
How create additional fields like address, mobile no

**Comment by REJack** [comment]
You can use the set_user_var/get_user_var 
$this->aauth->set_user_var('address', $value, FALSE); //FALSE == $user_id if false use loggedin user_id
$this->aauth->get_user_var('address', FALSE); //FALSE == $user_id if false use loggedin user_id

**Comment by vipinks** [comment]
One more solution For that situation may be using a custom table "profiles" for user's additional data by setting foreign key on  a column user_id in profiles table and you will be able to save any datatype in that table.

**Comment by emreakay** [comment]
@vipinks set_user_var() and get_user_var() exactly functions are what you need.
Your solution purpuse may be very complicated, cause for system with a lot of user, may make database slow.
