### ISSUE TITLE
Admin Super user for only current company

### ISSUE THREAD

**Issue by lostlian** [emreakay/CodeIgniter-Aauth#65]
Hello,

I have an application where there 3 different users. Admin, Manager, Agent.

The problem is I see Admin has access to EVERYTHING, and i want to have access to everything but ONLY in his company and not able to see other customers data.

Example. There are 2 companies.

Coca-Cola and Pepsi.

Admin from coca cola should see EVERYTHING from Coca-Cola but he cant see anything from Pepsi. 

how to you recommend me to handle this function with CI Aauth?

**Comment by REJack** [comment]
use the admin only for You as the developer and create 2 more groups and create premissions to keep the companies divided

**Comment by lostlian** [comment]
Thanks a lot for your reply. 

It makes a lot of sense. so you say to create 1 permission per company? (i have a company id column in each db table, so im able to know which company thr data is from)

**Comment by REJack** [comment]
i would write it like this:
```
if($this->aauth->control('pepsi')){
  $fetch = $this->db->get_where('your_db',array('company_id'=>'pepsi'));
}else if($this->aauth->control('coke')){
  $fetch = $this->db->get_where('your_db',array('company_id'=>'coke'));
}
```

**Comment by emreakay** [comment]
I am pleased to use our library @lostlian :+1: 
I am also thankful for your help @REJack
