### ISSUE TITLE
problem while using session driver as "database" and "use_cookies" true in aauth config

### ISSUE THREAD

**Issue by vipinks** [emreakay/CodeIgniter-Aauth#66]
I encountered a problem while using session driver as "database" in CI config file and "use_cookies" to true in aauth config file but leaving "recaptcha_active" to false. It throws error while logging in and that is "Sorry, the reCAPTCHA text entered was incorrect."
 As recaptcha_active is false, it must not do a check for that in login function. When session driver is set to "files", it works fine. Or is it not of any use in that that combination?

**Comment by REJack** [comment]
You should check if there is a cookie/session_tempdata named ``reCAPTCHA``.
Aauth search for it, if its there Aauth need reCAPTCHA data.
Aauth only creates a cookie or seesion tempdata if recaptcha_active is true.

**Comment by vipinks** [comment]
here is the session object via : - var_export($this->session); on login form
CI_Session::__set_state(array(
   'userdata' => 
  array (
    '__ci_last_regenerate' => 1444138349,
  ),
   '_driver' => 'database',
   '_config' => 
  array (
    'cookie_lifetime' => 7200,
    'cookie_name' => 'sarthak_sess',
    'cookie_path' => '/',
    'cookie_domain' => '',
    'cookie_secure' => false,
    'expiration' => 7200,
    'match_ip' => false,
    'save_path' => 'ci_sessions',
  ),
))
![aauth_error](https://cloud.githubusercontent.com/assets/1671608/10310049/90412418-6c5d-11e5-8616-21733e28c707.png)

**Comment by REJack** [comment]
Which version of CodeIgniter you use?

**Comment by vipinks** [comment]
v 3.0.1

**Comment by REJack** [comment]
use_cookies is true? If yes check for a reCAPTCHA cookie

**Comment by REJack** [comment]
idk this message should only appear if a reCAPTCHA cookie or session userdata(tempdata) is there.
i wrote a lil fix to check before if recapchta is enabled, you can test this.

https://github.com/REJack/CodeIgniter-Aauth/commit/9aca808dd70885e0d6c293189f015774cf031cf6

**Comment by vipinks** [comment]
Wow! that worked.

**Comment by REJack** [comment]
my fix?

**Comment by vipinks** [comment]
yes

**Comment by REJack** [comment]
i created a PR for it :+1:

**Comment by REJack** [comment]
@emreakay pls close this issue :smile:

**Comment by emreakay** [comment]
ok @REJack :dart:
