### ISSUE TITLE
I get "Key" is a reserved word in mysql

### ISSUE THREAD

**Issue by lostlian** [emreakay/CodeIgniter-Aauth#68]
Hello Guys,

I get this warning for the tables "aauth_user_variables" and "aauth_system_variables"

Does this affect anything?

**Comment by REJack** [comment]
i had never a error with this tables, but i write later a fix for it

Von meinem iPhone gesendet

**Comment by lostlian** [comment]
Thanks a lot :) its not an error, its a warning but i dont know it could cause any problems in the future. Thanks a lot for your fix.

**Comment by emreakay** [comment]
Thanks for all :)
