### ISSUE TITLE
What do you think of performance with large data and user variables?

### ISSUE THREAD

**Issue by lostlian** [emreakay/CodeIgniter-Aauth#72]
What do you think of performance with many users and user variables when doing joins?

**Comment by harishningegowda** [comment]
I am concerned of performance, hence I am not using user variables in my projects. I prefer creating another table with all the variables of users.

**Comment by REJack** [comment]
i have a project with round about 900 users and each user should have 25 user vars (16757 user vars in db). 

i need to say the performance is perfect but i dont know how i should check the performance :smiley: .
xls export over my php project with all users and user vars takes 10 seconds.

**Comment by REJack** [comment]
is your question awnsered? if yes pls close this issue :smile:

**Comment by lostlian** [comment]
Yes it is. Thanks a lot
