### ISSUE TITLE
Cookie expires not working

### ISSUE THREAD

**Issue by afbora** [emreakay/CodeIgniter-Aauth#79]
### Issue about lines:

https://github.com/emreakay/CodeIgniter-Aauth/blob/master/application/libraries/Aauth.php#L139
https://github.com/emreakay/CodeIgniter-Aauth/blob/master/application/libraries/Aauth.php#L193
https://github.com/emreakay/CodeIgniter-Aauth/blob/master/application/libraries/Aauth.php#L319
https://github.com/emreakay/CodeIgniter-Aauth/blob/master/application/libraries/Aauth.php#L334
https://github.com/emreakay/CodeIgniter-Aauth/blob/master/application/libraries/Aauth.php#L475

### According to the document:
http://www.codeigniter.com/user_guide/libraries/input.html?highlight=set_cookie#CI_Input::set_cookie

> $expire (int) – Cookie expiration time in seconds

**Current format is wrong:**

    'expire' => time() + 99*999*999

**Right format as integer:**

    'expire' => 99*999*999

I tested this issue on "remember me" function and it was not working. After fixed, its working now!

**Comment by REJack** [comment]
thx for the info i created a PR for it.

**Comment by emreakay** [comment]
thank you very much @afbora and @REJack :+1:
