### ISSUE TITLE
Invalid new config file

### ISSUE THREAD

**Issue by afbora** [emreakay/CodeIgniter-Aauth#81]
**Wrong format:**

    ['no_permission'] = FALSE,
    ['admin_group'] = 'admin',
    ...
    ...

**Right format:**

    'no_permission' => FALSE,
    'admin_group' => 'admin',
    ...
    ...

First wrong format may be true on PHP 5.6 but this is so unnecessary. I'm using PHP 5.4 and it doest work!

**Comment by REJack** [comment]
added a PR for it

**Comment by emreakay** [comment]
Thank you for your declaration. i'll merge the pr
