### ISSUE TITLE
What happened with fire_member method?

### ISSUE THREAD

**Issue by web-picker** [emreakay/CodeIgniter-Aauth#87]
I can't find fire_member method inside Aauth.php.
Would you check it please?

**Comment by REJack** [comment]
@web-picker

Look at the Wiki 'Migration from V1' 
https://github.com/emreakay/CodeIgniter-Aauth/wiki/1)-Migration-from-V1

it was replace/renamed with remove_member

Von meinem iPhone gesendet

**Comment by web-picker** [comment]
Thanks, I just was looking at example.php with fire_member method.
