### ISSUE TITLE
allow_user and allow_group problem

### ISSUE THREAD

**Issue by web-picker** [emreakay/CodeIgniter-Aauth#90]
I found problem when not existing permission is defined as $perm_par parameter inside allow_user function. get_perm_id returns FALSE if permission is not defined in DB, and you forgot to check it inside allow_user function. After I run allow_user( "user_id", "dummy_per" ), perm_to_user table contains data with perm_id=0 value. allow_group has same problem, so would you like to check it please?

**Comment by REJack** [comment]
i found the failure and wrote a PR for it incl check for group in allow_group :+1:

**Comment by web-picker** [comment]
Thank you. I saw the PR and i think it should be "return FALSE;" not TRUE. Because dummy group or permission is not expected result.

**Comment by REJack** [comment]
thx ^^ i saw it and fixed it right now :sweat_smile:

**Comment by web-picker** [comment]
Thanks!

**Comment by REJack** [comment]
@emreakay can you close this? it has a reference to #91 that you merged :smiley:

**Comment by emreakay** [comment]
thank you everyone. closed
