### ISSUE TITLE
We have reach to 100 stars :)

### ISSUE THREAD

**Issue by emreakay** [emreakay/CodeIgniter-Aauth#92]
Hi all Aauth Contribitors;

Today is very good day for our comunity.
We have reach 100 stars :+1: 

I want to thank all especially to @REJack @jacobtomlinson @tswagger @ManeBit @foksisko @afbora and @web-picker for their contribition

**Comment by REJack** [comment]
Thats really great :smiley: 
I will create in the next few months a PR for my major update of Aauth.

**Comment by emreakay** [comment]
we are waiting for you @REJack :+1:

**Comment by scombat** [comment]
Good Work all :) !
I hope stars will grow up more !

**Comment by pm-steiner** [comment]
Awesome lib, awesome people.  :+1:

**Comment by emreakay** [comment]
closed
