### ISSUE TITLE
How to make email based usernames?

### ISSUE THREAD

**Issue by dysk0** [emreakay/CodeIgniter-Aauth#94]
I want to use email as username and name column as users Firs and Last name? Is it possible withouth a lot of changes or just simply to use user variables?

**Comment by REJack** [comment]
you can also ignore the name field its not really important, only if you want to use a name as login

if you want to fill a email in the name field you need to add in the aauth config ``@``, ``-``, ``_ `` & ``.`` and to valid chars

**Comment by emreakay** [comment]
closed
